services:
  gitlab:
    image: gitlab/gitlab-ce:18.11.9-ce.0
    container_name: ghlove-gitlab
    hostname: localhost
    restart: unless-stopped
    shm_size: "256m"
    ports:
      - "8929:8929"
      - "2224:22"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost:8929'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab

volumes:
  gitlab_config:
  gitlab_logs:
  gitlab_data:
