-- AS-IS OP_COMMON_CODE 전량 적재 (운영DB export: OP_COMMON_CODE_202610021804.sql, UTF-8).
-- AS-IS 매퍼 60곳이 FROM OP_COMMON_CODE 로 화면 셀렉트박스 옵션을 읽는다. 옵션 값/라벨/정렬을
-- 내가 추정하지 않으려면 이 표가 선결조건이다([[copy-as-is-verbatim-never-invent]]).
-- admin.op_common_code는 컬럼 11개가 AS-IS와 완전히 동일하고 비어 있어 그대로 넣는다.
-- 주의: donation/member/ord/point 스키마의 op_common_code는 TO-BE가 의도적으로 만든 의미코드
-- 시드(BSNS_PURPS_CODE 등)라 건드리지 않는다. 재실행 가능(admin 스키마만 전체 교체).
TRUNCATE admin.op_common_code;

INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('11ST_DELIVERY_COMPANY','ko','00001','동부익스프레스',NULL,1,'Y',NULL,NULL,NULL,NULL),
	 ('11ST_DELIVERY_COMPANY','ko','00002','로젠택배',NULL,2,'Y',NULL,NULL,NULL,NULL),
	 ('11ST_DELIVERY_COMPANY','ko','00006','옐로우캡',NULL,3,'Y',NULL,NULL,NULL,NULL),
	 ('11ST_DELIVERY_COMPANY','ko','00007','우체국택배',NULL,4,'Y',NULL,NULL,NULL,NULL),
	 ('11ST_DELIVERY_COMPANY','ko','00008','우편등기',NULL,5,'Y',NULL,NULL,NULL,NULL),
	 ('11ST_DELIVERY_COMPANY','ko','00011','한진택배',NULL,6,'Y',NULL,NULL,NULL,NULL),
	 ('11ST_DELIVERY_COMPANY','ko','00012','현대택배',NULL,7,'Y',NULL,NULL,NULL,NULL),
	 ('11ST_DELIVERY_COMPANY','ko','00014','KGB택배',NULL,8,'Y',NULL,NULL,NULL,NULL),
	 ('11ST_DELIVERY_COMPANY','ko','00019','이노지스택배',NULL,9,'Y',NULL,NULL,NULL,NULL),
	 ('11ST_DELIVERY_COMPANY','ko','00021','대신택배',NULL,10,'Y',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('11ST_DELIVERY_COMPANY','ko','00022','일양로지스',NULL,11,'Y',NULL,NULL,NULL,NULL),
	 ('11ST_DELIVERY_COMPANY','ko','00023','ACI',NULL,12,'Y',NULL,NULL,NULL,NULL),
	 ('11ST_DELIVERY_COMPANY','ko','00025','WIZWA',NULL,13,'Y',NULL,NULL,NULL,NULL),
	 ('11ST_DELIVERY_COMPANY','ko','00026','경동택배',NULL,14,'Y',NULL,NULL,NULL,NULL),
	 ('11ST_DELIVERY_COMPANY','ko','00027','천일택배',NULL,15,'Y',NULL,NULL,NULL,NULL),
	 ('11ST_DELIVERY_COMPANY','ko','00028','KGL',NULL,16,'Y',NULL,NULL,NULL,NULL),
	 ('11ST_DELIVERY_COMPANY','ko','00031','OCS Korea',NULL,17,'Y',NULL,NULL,NULL,NULL),
	 ('11ST_DELIVERY_COMPANY','ko','00033','GTX택배',NULL,18,'Y',NULL,NULL,NULL,NULL),
	 ('11ST_DELIVERY_COMPANY','ko','00034','CJ대한통운',NULL,19,'Y',NULL,NULL,NULL,NULL),
	 ('11ST_DELIVERY_COMPANY','ko','00035','합동택배',NULL,20,'Y',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('11ST_DELIVERY_COMPANY','ko','00037','건영택배',NULL,21,'Y',NULL,NULL,NULL,NULL),
	 ('11ST_DELIVERY_COMPANY','ko','00099','기타',NULL,22,'Y',NULL,NULL,NULL,NULL),
	 ('ALLOW_IP','ko','0:0:0:0:0:0:0:1','온라인파워스','20191108||온파',NULL,'Y',NULL,NULL,NULL,NULL),
	 ('AUCTION_DELIVERY_COMPANY','ko','ajutb','동원로엑스택배',NULL,1,'N',NULL,NULL,NULL,NULL),
	 ('AUCTION_DELIVERY_COMPANY','ko','chonil','천일택배',NULL,2,'Y',NULL,NULL,NULL,NULL),
	 ('AUCTION_DELIVERY_COMPANY','ko','cjgls','CJ GLS택배',NULL,3,'Y',NULL,NULL,NULL,NULL),
	 ('AUCTION_DELIVERY_COMPANY','ko','cvsnet','편의점택배',NULL,4,'N',NULL,NULL,NULL,NULL),
	 ('AUCTION_DELIVERY_COMPANY','ko','daesin','대신택배',NULL,5,'Y',NULL,NULL,NULL,NULL),
	 ('AUCTION_DELIVERY_COMPANY','ko','dongbu','동부익스프레스택배',NULL,6,'Y',NULL,NULL,NULL,NULL),
	 ('AUCTION_DELIVERY_COMPANY','ko','epost','우체국택배',NULL,7,'Y',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('AUCTION_DELIVERY_COMPANY','ko','etc','기타',NULL,8,'N',NULL,NULL,NULL,NULL),
	 ('AUCTION_DELIVERY_COMPANY','ko','gmgls','굿모닝택배',NULL,9,'N',NULL,NULL,NULL,NULL),
	 ('AUCTION_DELIVERY_COMPANY','ko','gtx','GTX택배',NULL,10,'Y',NULL,NULL,NULL,NULL),
	 ('AUCTION_DELIVERY_COMPANY','ko','hanaro','하나로로지스',NULL,11,'Y',NULL,NULL,NULL,NULL),
	 ('AUCTION_DELIVERY_COMPANY','ko','hanjin','한진택배',NULL,12,'Y',NULL,NULL,NULL,NULL),
	 ('AUCTION_DELIVERY_COMPANY','ko','hapdong','합동택배',NULL,13,'N',NULL,NULL,NULL,NULL),
	 ('AUCTION_DELIVERY_COMPANY','ko','hth','CJ GLS택배',NULL,14,'N',NULL,NULL,NULL,NULL),
	 ('AUCTION_DELIVERY_COMPANY','ko','hyundai','현대택배',NULL,15,'Y',NULL,NULL,NULL,NULL),
	 ('AUCTION_DELIVERY_COMPANY','ko','ilyang','일양로지스',NULL,16,'Y',NULL,NULL,NULL,NULL),
	 ('AUCTION_DELIVERY_COMPANY','ko','innogis','이노지스택배',NULL,17,'Y',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('AUCTION_DELIVERY_COMPANY','ko','kgb','로젠택배',NULL,18,'Y',NULL,NULL,NULL,NULL),
	 ('AUCTION_DELIVERY_COMPANY','ko','kgbls','KGB택배',NULL,19,'Y',NULL,NULL,NULL,NULL),
	 ('AUCTION_DELIVERY_COMPANY','ko','korex','대한통운택배',NULL,20,'Y',NULL,NULL,NULL,NULL),
	 ('AUCTION_DELIVERY_COMPANY','ko','ktlogistics','KT로지스',NULL,21,'N',NULL,NULL,NULL,NULL),
	 ('AUCTION_DELIVERY_COMPANY','ko','kyungdong','경동택배',NULL,22,'Y',NULL,NULL,NULL,NULL),
	 ('AUCTION_DELIVERY_COMPANY','ko','lgelec','LG전자물류',NULL,23,'N',NULL,NULL,NULL,NULL),
	 ('AUCTION_DELIVERY_COMPANY','ko','nedex','한진택배',NULL,24,'Y',NULL,NULL,NULL,NULL),
	 ('AUCTION_DELIVERY_COMPANY','ko','sagawa','SC로지스(사가와)',NULL,25,'Y',NULL,NULL,NULL,NULL),
	 ('AUCTION_DELIVERY_COMPANY','ko','samsung','삼성전자물류',NULL,26,'N',NULL,NULL,NULL,NULL),
	 ('AUCTION_DELIVERY_COMPANY','ko','sedex','한진택배',NULL,27,'Y',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('AUCTION_DELIVERY_COMPANY','ko','tgs','TGS',NULL,28,'Y',NULL,NULL,NULL,NULL),
	 ('AUCTION_DELIVERY_COMPANY','ko','yellow','옐로우캡',NULL,29,'Y',NULL,NULL,NULL,NULL),
	 ('BUSINESS_SUB_TYPE','ko','101','사회복지(일반)','사회복지(일반)',1,'Y','100',NULL,NULL,NULL),
	 ('BUSINESS_SUB_TYPE','ko','102','사회복지(노인)','사회복지(노인)',2,'Y','100',NULL,NULL,NULL),
	 ('BUSINESS_SUB_TYPE','ko','103','사회복지(장애인)','사회복지(장애인)',3,'Y','100',NULL,NULL,NULL),
	 ('BUSINESS_SUB_TYPE','ko','104','사회복지(여성)','사회복지(여성)',4,'Y','100',NULL,NULL,NULL),
	 ('BUSINESS_SUB_TYPE','ko','105','사회복지(청소년)','사회복지(청소년)',5,'Y','100',NULL,NULL,NULL),
	 ('BUSINESS_SUB_TYPE','ko','106','사회복지(교육ㆍ육아)','사회복지(교육ㆍ육아)',6,'Y','100',NULL,NULL,NULL),
	 ('BUSINESS_SUB_TYPE','ko','107','저출산 고령화','저출산 고령화',7,'Y','100',NULL,NULL,NULL),
	 ('BUSINESS_SUB_TYPE','ko','108','기타','기타',8,'Y','100',NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('BUSINESS_SUB_TYPE','ko','201','보건ㆍ의료','보건ㆍ의료',1,'Y','200',NULL,NULL,NULL),
	 ('BUSINESS_SUB_TYPE','ko','202','건강','건강',2,'Y','200',NULL,NULL,NULL),
	 ('BUSINESS_SUB_TYPE','ko','203','문화','문화',3,'Y','200',NULL,NULL,NULL),
	 ('BUSINESS_SUB_TYPE','ko','204','예술','예술',4,'Y','200',NULL,NULL,NULL),
	 ('BUSINESS_SUB_TYPE','ko','205','체육','체육',5,'Y','200',NULL,NULL,NULL),
	 ('BUSINESS_SUB_TYPE','ko','206','관광','관광',6,'Y','200',NULL,NULL,NULL),
	 ('BUSINESS_SUB_TYPE','ko','207','기타','기타',7,'Y','200',NULL,NULL,NULL),
	 ('BUSINESS_SUB_TYPE','ko','301','마을 만들기','마을 만들기',1,'Y','300',NULL,NULL,NULL),
	 ('BUSINESS_SUB_TYPE','ko','302','정주 여건 개선','정주 여건 개선',2,'Y','300',NULL,NULL,NULL),
	 ('BUSINESS_SUB_TYPE','ko','303','환경개선(보호)','환경개선(보호)',3,'Y','300',NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('BUSINESS_SUB_TYPE','ko','304','낙후지역 개발','낙후지역 개발',4,'Y','300',NULL,NULL,NULL),
	 ('BUSINESS_SUB_TYPE','ko','305','안전ㆍ재난','안전ㆍ재난',5,'Y','300',NULL,NULL,NULL),
	 ('BUSINESS_SUB_TYPE','ko','306','재해 지원사업','재해 지원사업',6,'Y','300',NULL,NULL,NULL),
	 ('BUSINESS_SUB_TYPE','ko','401','인재육성','인재육성',1,'Y','400',NULL,NULL,NULL),
	 ('BUSINESS_SUB_TYPE','ko','402','균형발전을 위한 생활 SOC','균형발전을 위한 생활 SOC',2,'Y','400',NULL,NULL,NULL),
	 ('BUSINESS_SUB_TYPE','ko','403','기타','기타',3,'Y','400',NULL,NULL,NULL),
	 ('BUSINESS_TYPE','ko','100','취약계층','사회적 취약계층의 지원 및 청소년의 육성ㆍ보호',1,'Y',NULL,NULL,NULL,NULL),
	 ('BUSINESS_TYPE','ko','200','문화ㆍ예술ㆍ보건','지역 주민의 문화ㆍ예술ㆍ보건 등의 증진',2,'Y',NULL,NULL,NULL,NULL),
	 ('BUSINESS_TYPE','ko','300','자원봉사','시민참여, 자원봉사 등 지역공동체 활성화 지원(주민참여형 사업)',3,'Y',NULL,NULL,NULL,NULL),
	 ('BUSINESS_TYPE','ko','400','복리증진','그 밖에 주민의 복리 증진에 필요한 사업의 추진(취약계층, 문화ㆍ예술ㆍ보건, 자원봉사에 포함되지 않는 부문)',4,'Y',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('CANCEL_REASON','ko','1','구매의사 없음','2',NULL,'Y',NULL,NULL,NULL,NULL),
	 ('CANCEL_REASON','ko','2','판매자의 다른상품 주문','2',NULL,'Y',NULL,NULL,NULL,NULL),
	 ('CANCEL_REASON','ko','3','상품, 옵션등 선택 실수','2',NULL,'Y',NULL,NULL,NULL,NULL),
	 ('CANCEL_REASON','ko','4','기타','2',NULL,'N',NULL,NULL,NULL,NULL),
	 ('CANCEL_REASON','ko','5','결제수단변경','2',NULL,'Y',NULL,NULL,NULL,NULL),
	 ('CANCEL_REASON','ko','6','구매정보변경','2',NULL,'Y',NULL,NULL,NULL,NULL),
	 ('CANCEL_REASON','ko','7','기타','2',NULL,'Y',NULL,NULL,NULL,NULL),
	 ('CFM_STATUS','ko','100','승인',NULL,1,'Y',NULL,NULL,NULL,NULL),
	 ('CFM_STATUS','ko','200','대기',NULL,2,'Y',NULL,NULL,NULL,NULL),
	 ('CFM_STATUS','ko','300','거절',NULL,3,'Y',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('CJ_BANK_LIST','ko','003','기업은행',NULL,6,'Y',NULL,NULL,NULL,NULL),
	 ('CJ_BANK_LIST','ko','004','국민은행',NULL,1,'Y',NULL,NULL,NULL,NULL),
	 ('CJ_BANK_LIST','ko','007','수협',NULL,8,'Y',NULL,NULL,NULL,NULL),
	 ('CJ_BANK_LIST','ko','011','농협',NULL,2,'Y',NULL,NULL,NULL,NULL),
	 ('CJ_BANK_LIST','ko','020','우리은행',NULL,9,'Y',NULL,NULL,NULL,NULL),
	 ('CJ_BANK_LIST','ko','031','대구은행',NULL,10,'Y',NULL,NULL,NULL,NULL),
	 ('CJ_BANK_LIST','ko','032','부산은행',NULL,16,'Y',NULL,NULL,NULL,NULL),
	 ('CJ_BANK_LIST','ko','039','광주은행',NULL,17,'Y',NULL,NULL,NULL,NULL),
	 ('CJ_BANK_LIST','ko','040','제주은행','',18,'Y','','','',''),
	 ('CJ_BANK_LIST','ko','041','케이뱅크','',19,'Y','','','','');
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('CJ_BANK_LIST','ko','042','카카오뱅크','',21,'Y','','','',''),
	 ('CJ_BANK_LIST','ko','043','토스뱅크','',22,'Y','','','',''),
	 ('CJ_BANK_LIST','ko','044','SC제일은행','',23,'Y','','','',''),
	 ('CJ_BANK_LIST','ko','045','한국씨티은행','',24,'Y','','','',''),
	 ('CJ_BANK_LIST','ko','046','경남은행','',25,'Y','','','',''),
	 ('CJ_BANK_LIST','ko','047','전북은행','',26,'Y','','','',''),
	 ('CJ_BANK_LIST','ko','048','산업은행','',27,'Y','','','',''),
	 ('CJ_BANK_LIST','ko','049','새마을금고','',28,'Y','','','',''),
	 ('CJ_BANK_LIST','ko','050','신용협동조합','',29,'Y','','','',''),
	 ('CJ_BANK_LIST','ko','051','SJ산림조합중앙회','',30,'Y','','','','');
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('CJ_BANK_LIST','ko','071','우체국',NULL,3,'Y',NULL,NULL,NULL,NULL),
	 ('CJ_BANK_LIST','ko','081','하나은행',NULL,4,'Y',NULL,NULL,NULL,NULL),
	 ('CJ_BANK_LIST','ko','088','신한은행',NULL,5,'Y',NULL,NULL,NULL,NULL),
	 ('CLAIM_STATUS_CANCEL','ko','01','신청',NULL,1,'Y',NULL,NULL,NULL,NULL),
	 ('CLAIM_STATUS_CANCEL','ko','02','보류',NULL,2,'Y',NULL,NULL,NULL,NULL),
	 ('CLAIM_STATUS_CANCEL','ko','03','환불대기',NULL,3,'Y',NULL,NULL,NULL,NULL),
	 ('CLAIM_STATUS_CANCEL','ko','04','완료',NULL,4,'Y',NULL,NULL,NULL,NULL),
	 ('CLAIM_STATUS_CANCEL','ko','99','거절',NULL,5,'Y',NULL,NULL,NULL,NULL),
	 ('CLAIM_STATUS_EXCHANGE','ko','01','신청',NULL,1,'Y',NULL,NULL,NULL,NULL),
	 ('CLAIM_STATUS_EXCHANGE','ko','02','보류',NULL,2,'Y',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('CLAIM_STATUS_EXCHANGE','ko','03','교환상품 발송',NULL,6,'Y',NULL,NULL,NULL,NULL),
	 ('CLAIM_STATUS_EXCHANGE','ko','04','교환완료','',7,'Y',NULL,NULL,NULL,NULL),
	 ('CLAIM_STATUS_EXCHANGE','ko','10','회수중',NULL,3,'Y',NULL,NULL,NULL,NULL),
	 ('CLAIM_STATUS_EXCHANGE','ko','11','회수완료',NULL,4,'Y',NULL,NULL,NULL,NULL),
	 ('CLAIM_STATUS_EXCHANGE','ko','99','거절',NULL,5,'Y',NULL,NULL,NULL,NULL),
	 ('CLAIM_STATUS_RETURN','ko','01','신청',NULL,1,'Y',NULL,NULL,NULL,NULL),
	 ('CLAIM_STATUS_RETURN','ko','02','보류',NULL,2,'Y',NULL,NULL,NULL,NULL),
	 ('CLAIM_STATUS_RETURN','ko','03','환불승인 대기',NULL,6,'Y',NULL,NULL,NULL,NULL),
	 ('CLAIM_STATUS_RETURN','ko','04','환불완료',NULL,7,'Y',NULL,NULL,NULL,NULL),
	 ('CLAIM_STATUS_RETURN','ko','10','회수중',NULL,3,'Y',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('CLAIM_STATUS_RETURN','ko','11','회수완료',NULL,4,'Y',NULL,NULL,NULL,NULL),
	 ('CLAIM_STATUS_RETURN','ko','99','거절',NULL,5,'Y',NULL,NULL,NULL,NULL),
	 ('CNTR_PATH','ko','100','온라인',NULL,1,'Y',NULL,NULL,NULL,NULL),
	 ('CNTR_PATH','ko','200','오프라인',NULL,2,'Y',NULL,NULL,NULL,NULL),
	 ('CNTR_REQMNG','ko','100','과오납','기부 과오납 처리',1,'Y',NULL,NULL,NULL,NULL),
	 ('CNTR_REQMNG','ko','200','포인트생성','답례품여부변경에 따른 포인트 생성',2,'Y',NULL,NULL,NULL,NULL),
	 ('CNTR_REQMNG','ko','300','수납처리','삭제여부 변경 및 수납처리',3,'Y','','','',''),
	 ('CNTR_REQMNG','ko','400','수납취소','기부 신고 내역 수납 취소',4,'Y','','','',''),
	 ('CNTR_STTUS','ko','100','미수납','기부 신고',1,'Y','','','',''),
	 ('CNTR_STTUS','ko','200','수납','납부완료',2,'Y','','','','');
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('CNTR_STTUS','ko','300','과오납','기부 과오납 처리',3,'Y',NULL,NULL,NULL,NULL),
	 ('CNTR_STTUS','ko','900','배치처리','수납확인 배치 처리',9,'Y',NULL,NULL,NULL,NULL),
	 ('CNTR_USE','ko','100','사회적 취약계층의 지원 및 청소년의 육성ㆍ보호',NULL,1,'Y',NULL,NULL,NULL,NULL),
	 ('CNTR_USE','ko','200','지역 주민의 문화ㆍ예술ㆍ보건 등의 증진',NULL,2,'Y',NULL,NULL,NULL,NULL),
	 ('CNTR_USE','ko','300','시민참여, 자원봉사 등 지역공동체 활성화 지원',NULL,3,'Y',NULL,NULL,NULL,NULL),
	 ('CNTR_USE','ko','400','그 밖에 주민의 복리 증진에 필요한 사업의 추진',NULL,4,'Y',NULL,NULL,NULL,NULL),
	 ('CONB_CD','ko','43','일반지역기부','일반지역기부',1,'Y',NULL,NULL,NULL,NULL),
	 ('CONB_CD','ko','44','특별재난지역기부','특별재난지역기부',2,'Y',NULL,NULL,NULL,NULL),
	 ('DEFAULT_BANK_LIST','ko','SC','SC은행',NULL,6,'Y',NULL,NULL,NULL,NULL),
	 ('DEFAULT_BANK_LIST','ko','경남','경남은행',NULL,11,'Y',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('DEFAULT_BANK_LIST','ko','광주','광주은행',NULL,10,'Y',NULL,NULL,NULL,NULL),
	 ('DEFAULT_BANK_LIST','ko','국민','KB국민은행',NULL,2,'Y',NULL,NULL,NULL,NULL),
	 ('DEFAULT_BANK_LIST','ko','기업','기업은행',NULL,1,'Y',NULL,NULL,NULL,NULL),
	 ('DEFAULT_BANK_LIST','ko','농축협','농축협',NULL,5,'Y',NULL,NULL,NULL,NULL),
	 ('DEFAULT_BANK_LIST','ko','농협','NH농협',NULL,4,'Y',NULL,NULL,NULL,NULL),
	 ('DEFAULT_BANK_LIST','ko','대구','대구은행',NULL,8,'Y',NULL,NULL,NULL,NULL),
	 ('DEFAULT_BANK_LIST','ko','부산','부산은행',NULL,9,'Y',NULL,NULL,NULL,NULL),
	 ('DEFAULT_BANK_LIST','ko','수협','수협',NULL,3,'Y',NULL,NULL,NULL,NULL),
	 ('DEFAULT_BANK_LIST','ko','신한','신한은행',NULL,14,'Y',NULL,NULL,NULL,NULL),
	 ('DEFAULT_BANK_LIST','ko','씨티','한국씨티은행',NULL,7,'Y',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('DEFAULT_BANK_LIST','ko','우리','우리은행',NULL,5,'Y',NULL,NULL,NULL,NULL),
	 ('DEFAULT_BANK_LIST','ko','우체국','우체국',NULL,12,'Y',NULL,NULL,NULL,NULL),
	 ('DEFAULT_BANK_LIST','ko','하나','KEB하나은행',NULL,13,'Y',NULL,NULL,NULL,NULL),
	 ('DONATION_LIMIT_AMT','ko','2024','20000000','2천만',3,'Y','','','',''),
	 ('DONATION_LIMIT_AMT','ko','2025','20000000','2천만',2,'Y','','','',''),
	 ('DONATION_LIMIT_AMT','ko','2026','20000000','2천만',1,'Y','','','',''),
	 ('DONATION_LIMIT_AMT','ko','2027','20000000','2천만',4,'Y','','','',''),
	 ('DONATION_LIMIT_AMT','ko','2028','20000000','2천만',5,'Y','','','',''),
	 ('DONATION_LIMIT_AMT','ko','2029','20000000','2천만',6,'Y','','','',''),
	 ('DONATION_LIMIT_AMT','ko','2030','20000000','2천만',7,'Y','','','','');
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('EMAIL','ko','0','직접입력','',1,'Y','','','',''),
	 ('EMAIL','ko','daum.net','daum.net','daum.net',2,'Y',NULL,NULL,NULL,NULL),
	 ('EMAIL','ko','dreamwiz.com','dreamwiz.com','dreamwiz.com',3,'Y',NULL,NULL,NULL,NULL),
	 ('EMAIL','ko','empas.com','empas.com','empas.com',4,'Y',NULL,NULL,NULL,NULL),
	 ('EMAIL','ko','freechal.com','freechal.com','freechal.com',5,'Y',NULL,NULL,NULL,NULL),
	 ('EMAIL','ko','gmail.com','gmail.com','gmail.com',6,'Y',NULL,NULL,NULL,NULL),
	 ('EMAIL','ko','hanmail.net','hanmail.net','hanmail.net',7,'Y',NULL,NULL,NULL,NULL),
	 ('EMAIL','ko','hanmir.com','hanmir.com','hanmir.com',8,'Y',NULL,NULL,NULL,NULL),
	 ('EMAIL','ko','hotmail.com','hotmail.com','hotmail.com',9,'Y',NULL,NULL,NULL,NULL),
	 ('EMAIL','ko','live.com','live.com','live.com',10,'Y',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('EMAIL','ko','lycos.co.kr','lycos.co.kr','lycos.co.kr',11,'Y',NULL,NULL,NULL,NULL),
	 ('EMAIL','ko','msn.com','msn.com','msn.com',12,'Y',NULL,NULL,NULL,NULL),
	 ('EMAIL','ko','nate.com','nate.com','nate.com',13,'Y',NULL,NULL,NULL,NULL),
	 ('EMAIL','ko','naver.com','naver.com','naver.com',14,'Y',NULL,NULL,NULL,NULL),
	 ('EMAIL','ko','netian.com','netian.com','netian.com',15,'Y',NULL,NULL,NULL,NULL),
	 ('EMAIL','ko','outlook.com','outlook.com','outlook.com',16,'Y',NULL,NULL,NULL,NULL),
	 ('EMAIL','ko','paran.com','paran.com','paran.com',17,'Y',NULL,NULL,NULL,NULL),
	 ('EMAIL','ko','yahoo.co.kr','yahoo.co.kr','yahoo.co.kr',18,'Y',NULL,NULL,NULL,NULL),
	 ('EMAIL_STATUS','ko','C','전송완료','',4,'Y','','','',''),
	 ('EMAIL_STATUS','ko','F','발송요청실패','',3,'Y','','','','');
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('EMAIL_STATUS','ko','P','전송실패','',5,'Y','','','',''),
	 ('EMAIL_STATUS','ko','R','발송요청','',1,'Y','','','',''),
	 ('EMAIL_STATUS','ko','S','발송요청성공','',2,'Y','','','',''),
	 ('EMAIL_STATUS','ko','T','전송일부성공','',6,'Y','','','',''),
	 ('EXCELDOWNLOAD_REASON_TYPE','ko','1','기부금 모금 실적 확인',NULL,1,'Y',NULL,NULL,NULL,NULL),
	 ('EXCELDOWNLOAD_REASON_TYPE','ko','2','답례품 주문내역 확인',NULL,2,'Y',NULL,NULL,NULL,NULL),
	 ('EXCELDOWNLOAD_REASON_TYPE','ko','3','택배 송장 출력 및 배송확인',NULL,3,'Y',NULL,NULL,NULL,NULL),
	 ('EXCELDOWNLOAD_REASON_TYPE','ko','4','답례품 정산 및 지급 확인',NULL,4,'Y',NULL,NULL,NULL,NULL),
	 ('EXCELDOWNLOAD_REASON_TYPE','ko','5','기타',NULL,5,'Y',NULL,NULL,NULL,NULL),
	 ('EXCHANGE_REASON','ko','1','상품, 옵션등의 변경','2',NULL,'Y',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('EXCHANGE_REASON','ko','2','상품 파손','1',NULL,'Y',NULL,NULL,NULL,NULL),
	 ('EXCHANGE_REASON','ko','3','상품이 잘못 배송됨','1',NULL,'Y',NULL,NULL,NULL,NULL),
	 ('EXCHANGE_REASON','ko','4','기타','2',NULL,'N',NULL,NULL,NULL,NULL),
	 ('EXCHANGE_REASON','ko','5','상품누락/오배송','2',NULL,'Y',NULL,NULL,NULL,NULL),
	 ('EXCHANGE_REASON','ko','6','기타','2',NULL,'Y',NULL,NULL,NULL,NULL),
	 ('FAQ_TYPE','ko','1','회원정보',NULL,1,'Y',NULL,NULL,NULL,NULL),
	 ('FAQ_TYPE','ko','2','주문/결제',NULL,2,'Y',NULL,NULL,NULL,NULL),
	 ('FAQ_TYPE','ko','3','배송',NULL,3,'Y',NULL,NULL,NULL,NULL),
	 ('FAQ_TYPE','ko','4','교환/반품/수리',NULL,4,'Y',NULL,NULL,NULL,NULL),
	 ('FAQ_TYPE','ko','5','포인트',NULL,5,'Y',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('FAQ_TYPE','ko','6','기타',NULL,6,'Y',NULL,NULL,NULL,NULL),
	 ('HNR_USER_SLCTN_SE_CD','ko','BF_YR_1YR','기준 1','전년도 기부 금액이 발급기준금액 충족 시 해당 연도 1년 간 기부혜택증 발급',1,'Y',NULL,NULL,NULL,NULL),
	 ('HNR_USER_SLCTN_SE_CD','ko','JEJU_REQ_CRTR','기준 3','동일 회계연도 내 기부 금액이 발급기준금액 충족 시 1년 간 기부혜택증 발급',3,'Y',NULL,NULL,NULL,NULL),
	 ('HNR_USER_SLCTN_SE_CD','ko','NOW_CRTR_1YR_WTHN','기준 2','최근 1년 간 기부 금액이 발급기준금액 충족 시 기부혜택증 발급',2,'Y',NULL,NULL,NULL,NULL),
	 ('HONOR_STD','ko','100','우수','',1,'Y','','','',''),
	 ('HONOR_STD','ko','200','최우수','',2,'Y','','','',''),
	 ('HONOR_STD','ko','300','특급','',3,'Y','','','',''),
	 ('INICIS_BANK_LIST','ko','03','기업은행','기업은행',5,'Y',NULL,NULL,NULL,NULL),
	 ('INICIS_BANK_LIST','ko','04','KB국민은행','KB국민은행',2,'Y',NULL,NULL,NULL,NULL),
	 ('INICIS_BANK_LIST','ko','07','수협중앙회','수협중앙회',14,'Y',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('INICIS_BANK_LIST','ko','11','NH농협은행','NH농협은행',1,'Y',NULL,NULL,NULL,NULL),
	 ('INICIS_BANK_LIST','ko','20','우리은행','우리은행',4,'Y',NULL,NULL,NULL,NULL),
	 ('INICIS_BANK_LIST','ko','23','SC은행','SC은행',11,'Y',NULL,NULL,NULL,NULL),
	 ('INICIS_BANK_LIST','ko','27','한국씨티은행','한국씨티은행',13,'Y',NULL,NULL,NULL,NULL),
	 ('INICIS_BANK_LIST','ko','31','대구은행','대구은행',7,'Y',NULL,NULL,NULL,NULL),
	 ('INICIS_BANK_LIST','ko','32','부산은행','부산은행',8,'Y',NULL,NULL,NULL,NULL),
	 ('INICIS_BANK_LIST','ko','34','광주은행','광주은행',10,'Y',NULL,NULL,NULL,NULL),
	 ('INICIS_BANK_LIST','ko','39','경남은행','경남은행',12,'Y',NULL,NULL,NULL,NULL),
	 ('INICIS_BANK_LIST','ko','71','우체국','우체국',9,'Y',NULL,NULL,NULL,NULL),
	 ('INICIS_BANK_LIST','ko','81','KEB 하나은행','KEB 하나은행',6,'Y',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('INICIS_BANK_LIST','ko','88','신한은행','신한은행',3,'Y',NULL,NULL,NULL,NULL),
	 ('INICIS_CARD_LIST','ko','01','하나(외환)','하나(외환)',1,'Y',NULL,NULL,NULL,NULL),
	 ('INICIS_CARD_LIST','ko','03','롯데','롯데',2,'Y',NULL,NULL,NULL,NULL),
	 ('INICIS_CARD_LIST','ko','04','현대','현대',3,'Y',NULL,NULL,NULL,NULL),
	 ('INICIS_CARD_LIST','ko','06','국민','국민',4,'Y',NULL,NULL,NULL,NULL),
	 ('INICIS_CARD_LIST','ko','11','BC','BC',5,'Y',NULL,NULL,NULL,NULL),
	 ('INICIS_CARD_LIST','ko','12','삼성','삼성',6,'Y',NULL,NULL,NULL,NULL),
	 ('INICIS_CARD_LIST','ko','14','신한','신한',7,'Y',NULL,NULL,NULL,NULL),
	 ('INICIS_CARD_LIST','ko','21','해외 VISA','해외 VISA',8,'Y',NULL,NULL,NULL,NULL),
	 ('INICIS_CARD_LIST','ko','22','해외마스터','해외마스터',9,'Y',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('INICIS_CARD_LIST','ko','23','해외 JCB','해외 JCB',10,'Y',NULL,NULL,NULL,NULL),
	 ('INICIS_CARD_LIST','ko','26','중국은련','중국은련',11,'Y',NULL,NULL,NULL,NULL),
	 ('INICIS_CARD_LIST','ko','32','광주','광주',12,'Y',NULL,NULL,NULL,NULL),
	 ('INICIS_CARD_LIST','ko','33','전북','전북',13,'Y',NULL,NULL,NULL,NULL),
	 ('INICIS_CARD_LIST','ko','34','하나','하나',14,'Y',NULL,NULL,NULL,NULL),
	 ('INICIS_CARD_LIST','ko','35','산업카드','산업카드',15,'Y',NULL,NULL,NULL,NULL),
	 ('INICIS_CARD_LIST','ko','41','NH','NH',16,'Y',NULL,NULL,NULL,NULL),
	 ('INICIS_CARD_LIST','ko','43','씨티','씨티',17,'Y',NULL,NULL,NULL,NULL),
	 ('INICIS_CARD_LIST','ko','44','우리','우리',18,'Y',NULL,NULL,NULL,NULL),
	 ('INICIS_CARD_LIST','ko','48','신협체크','신협체크',19,'Y',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('INICIS_CARD_LIST','ko','51','수협','수협',20,'Y',NULL,NULL,NULL,NULL),
	 ('INICIS_CARD_LIST','ko','52','제주','제주',21,'Y',NULL,NULL,NULL,NULL),
	 ('INICIS_CARD_LIST','ko','54','MG새마을금고체크','MG새마을금고체크',22,'Y',NULL,NULL,NULL,NULL),
	 ('INICIS_CARD_LIST','ko','71','우체국체크','우체국체크',23,'Y',NULL,NULL,NULL,NULL),
	 ('INICIS_CARD_LIST','ko','95','저축은행체크','저축은행체크',24,'Y',NULL,NULL,NULL,NULL),
	 ('ITEM_COLOR','ko','#0066cc','네이비 · 블루 계열',NULL,5,'Y',NULL,NULL,NULL,NULL),
	 ('ITEM_COLOR','ko','#008000','그린 계열',NULL,6,'Y',NULL,NULL,NULL,NULL),
	 ('ITEM_COLOR','ko','#333333','블랙 · 그레이 계열',NULL,8,'Y',NULL,NULL,NULL,NULL),
	 ('ITEM_COLOR','ko','#800080','라벤더 · 퍼플 계열',NULL,4,'Y',NULL,NULL,NULL,NULL),
	 ('ITEM_COLOR','ko','#969696','메탈릭 클리어 계열',NULL,10,'Y',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('ITEM_COLOR','ko','#993300','브라운 계열',NULL,7,'Y',NULL,NULL,NULL,NULL),
	 ('ITEM_COLOR','ko','#ff0000','핑크 · 레드 계열',NULL,3,'Y',NULL,NULL,NULL,NULL),
	 ('ITEM_COLOR','ko','#ffffcc','베이지 · 내츄럴 계열',NULL,2,'Y',NULL,NULL,NULL,NULL),
	 ('ITEM_COLOR','ko','#ffffff','화이트 계열',NULL,9,'Y',NULL,NULL,NULL,NULL),
	 ('ITEM_PRIVATE_TYPE','ko','00','일반회원',NULL,1,'Y',NULL,NULL,NULL,NULL),
	 ('ITEM_PRIVATE_TYPE','ko','01','로그인회원','ROLE_USER',2,'Y',NULL,NULL,NULL,NULL),
	 ('ITEM_PRIVATE_TYPE','ko','02','교사전용','A_GROUP,B_GROUP',3,'Y',NULL,NULL,NULL,NULL),
	 ('ITEM_PRIVATE_TYPE','ko','03','중학교 교사 전용','B_GROUP',4,'Y',NULL,NULL,NULL,NULL),
	 ('ITEM_PRIVATE_TYPE','ko','04','초등학교 교사 전용','A_GROUP',5,'Y',NULL,NULL,NULL,NULL),
	 ('LEAVE_CODE','ko','001','탈퇴 후 재가입을 위해서',NULL,1,'Y',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('LEAVE_CODE','ko','002','사고 싶은 상품이 없어서',NULL,2,'Y',NULL,NULL,NULL,NULL),
	 ('LEAVE_CODE','ko','003','자주 이용하지 않아서',NULL,3,'Y',NULL,NULL,NULL,NULL),
	 ('LEAVE_CODE','ko','004','서비스 및 고객지원이 만족스럽지 않아서',NULL,4,'Y',NULL,NULL,NULL,NULL),
	 ('LEAVE_CODE','ko','005','광고성 알림이 너무 많이 와서',NULL,5,'Y',NULL,NULL,NULL,NULL),
	 ('LGDACOM_BANK_LIST','ko','002','산업은행','산업은행',1,'Y',NULL,NULL,NULL,NULL),
	 ('LGDACOM_BANK_LIST','ko','003','기업은행','기업은행',2,'Y',NULL,NULL,NULL,NULL),
	 ('LGDACOM_BANK_LIST','ko','004','KB국민은행','KB국민은행',3,'Y',NULL,NULL,NULL,NULL),
	 ('LGDACOM_BANK_LIST','ko','007','수협중앙회','수협중앙회',4,'Y',NULL,NULL,NULL,NULL),
	 ('LGDACOM_BANK_LIST','ko','011','NH농협은행','NH농협은행',5,'Y',NULL,NULL,NULL,NULL),
	 ('LGDACOM_BANK_LIST','ko','020','우리은행','우리은행',6,'Y',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('LGDACOM_BANK_LIST','ko','023','SC제일은행','SC제일은행',7,'Y',NULL,NULL,NULL,NULL),
	 ('LGDACOM_BANK_LIST','ko','027','한국씨티은행','한국씨티은행',8,'Y',NULL,NULL,NULL,NULL),
	 ('LGDACOM_BANK_LIST','ko','031','대구은행','대구은행',9,'Y',NULL,NULL,NULL,NULL),
	 ('LGDACOM_BANK_LIST','ko','032','부산은행','부산은행',10,'Y',NULL,NULL,NULL,NULL),
	 ('LGDACOM_BANK_LIST','ko','034','광주은행','광주은행',11,'Y',NULL,NULL,NULL,NULL),
	 ('LGDACOM_BANK_LIST','ko','035','제주은행','제주은행',12,'Y',NULL,NULL,NULL,NULL),
	 ('LGDACOM_BANK_LIST','ko','037','전북은행','전북은행',13,'Y',NULL,NULL,NULL,NULL),
	 ('LGDACOM_BANK_LIST','ko','039','경남은행','경남은행',14,'Y',NULL,NULL,NULL,NULL),
	 ('LGDACOM_BANK_LIST','ko','045','새마을금고','새마을금고',15,'Y',NULL,NULL,NULL,NULL),
	 ('LGDACOM_BANK_LIST','ko','048','신협','신협',16,'Y',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('LGDACOM_BANK_LIST','ko','071','우체국','우체국',17,'Y',NULL,NULL,NULL,NULL),
	 ('LGDACOM_BANK_LIST','ko','081','KEB하나은행','KEB하나은행',18,'Y',NULL,NULL,NULL,NULL),
	 ('LGDACOM_BANK_LIST','ko','088','신한은행','신한은행',19,'Y',NULL,NULL,NULL,NULL),
	 ('LGDACOM_BANK_LIST','ko','209','동양증권','동양증권',20,'Y',NULL,NULL,NULL,NULL),
	 ('LGDACOM_BANK_LIST','ko','230','미래에셋','미래에셋',21,'Y',NULL,NULL,NULL,NULL),
	 ('LGDACOM_BANK_LIST','ko','240','삼성증권','삼성증권',22,'Y',NULL,NULL,NULL,NULL),
	 ('LGDACOM_BANK_LIST','ko','243','한국투자증권','한국투자증권',23,'Y',NULL,NULL,NULL,NULL),
	 ('LGDACOM_BANK_LIST','ko','269','한화증권','한화증권',24,'Y',NULL,NULL,NULL,NULL),
	 ('LGDACOM_BANK_LIST','ko','278','신한금융투자','신한금융투자',25,'Y',NULL,NULL,NULL,NULL),
	 ('LINK_INSTT_CD','ko','I0000000','디지털서비스플랫폼','디지털서비스플랫폼',1,'N','','','','');
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('LINK_INSTT_CD','ko','I0000001','㈜SR','㈜SR',2,'N',NULL,NULL,NULL,NULL),
	 ('LINK_INSTT_CD','ko','I0000002','한국교통안전공단','한국교통안전공단',3,'N',NULL,NULL,NULL,NULL),
	 ('LINK_INSTT_CD','ko','I0000003','국립자연휴양림관리소','국립자연휴양림관리소',4,'N',NULL,NULL,NULL,NULL),
	 ('LINK_INSTT_CD','ko','I0000004','국립수목원','국립수목원',5,'N',NULL,NULL,NULL,NULL),
	 ('LINK_INSTT_CD','ko','I0000005','한국수목원정원관리원','한국수목원정원관리원',6,'N',NULL,NULL,NULL,NULL),
	 ('LINK_INSTT_CD','ko','I0000006','인천국제공항공사','인천국제공항공사',7,'N',NULL,NULL,NULL,NULL),
	 ('LINK_INSTT_CD','ko','I0000007','한국문화예술위원회','한국문화예술위원회',8,'N',NULL,NULL,NULL,NULL),
	 ('LINK_INSTT_CD','ko','I0000008','네이버 주식회사','네이버 주식회사',9,'N',NULL,NULL,NULL,NULL),
	 ('LINK_INSTT_CD','ko','I0000009','네이버 파이낸셜(주)','네이버 파이낸셜(주)',10,'N',NULL,NULL,NULL,NULL),
	 ('LINK_INSTT_CD','ko','I0000010','카카오 모빌리티','카카오 모빌리티',11,'N',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('LINK_INSTT_CD','ko','I0000011','비바리퍼블리카','비바리퍼블리카',12,'N',NULL,NULL,NULL,NULL),
	 ('LINK_INSTT_CD','ko','I0000012','신한카드','신한카드',13,'N',NULL,NULL,NULL,NULL),
	 ('LINK_INSTT_CD','ko','I0000013','KB국민은행','KB국민은행',14,'Y','','','',''),
	 ('LINK_INSTT_CD','ko','I0000014','KB국민카드','KB국민카드',15,'N',NULL,NULL,NULL,NULL),
	 ('LINK_INSTT_CD','ko','I0000015','행정안전부','행정안전부',16,'N',NULL,NULL,NULL,NULL),
	 ('LINK_INSTT_CD','ko','I0000016','한국장학재단','한국장학재단',17,'N',NULL,NULL,NULL,NULL),
	 ('LINK_INSTT_CD','ko','I0000017','병무청','병무청',18,'N',NULL,NULL,NULL,NULL),
	 ('LINK_INSTT_CD','ko','I0000018','경찰청','경찰청',19,'N',NULL,NULL,NULL,NULL),
	 ('LINK_INSTT_CD','ko','I0000019','우리은행','우리은행',20,'N',NULL,NULL,NULL,NULL),
	 ('LINK_INSTT_CD','ko','I0000020','삼성카드','삼성카드',21,'N',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('LINK_INSTT_CD','ko','I0000021','한국지능정보사회진흥원','한국지능정보사회진흥원',22,'N',NULL,NULL,NULL,NULL),
	 ('LINK_INSTT_CD','ko','I0000022','카카오페이','카카오페이',23,'N',NULL,NULL,NULL,NULL),
	 ('LINK_INSTT_CD','ko','I0000023','공정거래위원회','공정거래위원회',24,'N',NULL,NULL,NULL,NULL),
	 ('LINK_INSTT_CD','ko','I0000024','국토교통부','국토교통부',25,'N',NULL,NULL,NULL,NULL),
	 ('LINK_INSTT_CD','ko','I0000025','한국도로공사','한국도로공사',26,'N',NULL,NULL,NULL,NULL),
	 ('LINK_INSTT_CD','ko','I0000026','한국환경공단','한국환경공단',27,'N',NULL,NULL,NULL,NULL),
	 ('LINK_INSTT_CD','ko','I0000027','도로교통공단','도로교통공단',28,'N',NULL,NULL,NULL,NULL),
	 ('LINK_INSTT_CD','ko','I0000028','산림청','산림청',29,'N',NULL,NULL,NULL,NULL),
	 ('LINK_INSTT_CD','ko','I0000029','국립생태원','국립생태원',30,'N',NULL,NULL,NULL,NULL),
	 ('LINK_INSTT_CD','ko','I0000030','질병관리청','질병관리청',31,'N',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('LINK_INSTT_CD','ko','I0000031','국세청','국세청',32,'N',NULL,NULL,NULL,NULL),
	 ('LINK_INSTT_CD','ko','I0000032','국립중앙도서관','국립중앙도서관',33,'N',NULL,NULL,NULL,NULL),
	 ('LINK_INSTT_CD','ko','I0000033','외교부','외교부',34,'N',NULL,NULL,NULL,NULL),
	 ('LINK_INSTT_CD','ko','I0000034','행정서비스 통합추진단','행정서비스 통합추진단',35,'N',NULL,NULL,NULL,NULL),
	 ('LINK_INSTT_CD','ko','I0000035','SKT','SKT',36,'N',NULL,NULL,NULL,NULL),
	 ('LINK_INSTT_CD','ko','I0000036','웰로','웰로',37,'Y',NULL,NULL,NULL,NULL),
	 ('LINK_INSTT_CD','ko','I0000037','신한은행','신한은행',38,'Y','','','',''),
	 ('LINK_INSTT_CD','ko','I0000038','KT','KT',39,'N',NULL,NULL,NULL,NULL),
	 ('LINK_INSTT_CD','ko','I0000039','LG U+','LG U+',40,'N',NULL,NULL,NULL,NULL),
	 ('LINK_INSTT_CD','ko','I0000043','행정안전부 균형발전진흥국 균형발전진흥과','고향사랑e음',41,'N',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('LINK_INSTT_CD','ko','I0000044','행정안전부 디지털정부실 공공서비스국 공공서비스통합과','행정안전부 디지털정부실 공공서비스국 공공서비스통합과',42,'N',NULL,NULL,NULL,NULL),
	 ('LINK_INSTT_CD','ko','I0000045','IBK기업은행','IBK기업은행',43,'Y','','','',''),
	 ('LINK_INSTT_CD','ko','I0000046','하나은행','하나은행',44,'Y','','','',''),
	 ('LINK_INSTT_CD','ko','I0000047','공감만세','위기브',45,'Y','','','',''),
	 ('LINK_INSTT_CD','ko','I0000048','액티부키','액티부키',46,'Y','','','',''),
	 ('LINK_INSTT_CD','ko','I0000049','NH농협은행','NH농협은행',47,'Y',NULL,NULL,NULL,NULL),
	 ('LINK_INSTT_CD','ko','I0000050','여성가족부 청소년활동진흥과(청소년 자원봉사)','여성가족부 청소년활동진흥과(청소년 자원봉사)',48,'N',NULL,NULL,NULL,NULL),
	 ('LINK_INSTT_CD','ko','I0000051','행정안전부 지방행정국 민간협력과(1365 자원봉사)','행정안전부 지방행정국 민간협력과(1365 자원봉사)',49,'N',NULL,NULL,NULL,NULL),
	 ('LINK_INSTT_CD','ko','I0000052','한국사회복지협회 자원봉사사업단(사회복지 자원봉사)','한국사회복지협회 자원봉사사업단(사회복지 자원봉사)',50,'N',NULL,NULL,NULL,NULL),
	 ('LINK_INSTT_CD','ko','I0000053','뱅크샐러드','뱅크샐러드',51,'N','','','','');
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('LINK_INSTT_CD','ko','I0000054','국립중앙박물관','국립중앙박물관',52,'N','','','',''),
	 ('LINK_INSTT_CD','ko','I0000055','한국지역정보개발원','한국지역정보개발원',53,'N','','','',''),
	 ('LINK_INSTT_CD','ko','I0000056','한국청소년활동진흥원','한국청소년활동진흥원',54,'N','','','',''),
	 ('LINK_INSTT_CD','ko','I0000057','해양수산부','해양수산부',55,'N','','','',''),
	 ('LINK_INSTT_CD','ko','I0000092','체리','체리',56,'Y',NULL,NULL,NULL,NULL),
	 ('LINK_INSTT_CD','ko','I0000108','정부24','디지털지갑',58,'Y',NULL,NULL,NULL,NULL),
	 ('LINK_INSTT_CD','ko','I0000118','디투홈','디투홈',57,'Y',NULL,NULL,NULL,NULL),
	 ('LINK_INSTT_CD','ko','I0000143','광주은행','광주은행',59,'Y',NULL,NULL,NULL,NULL),
	 ('LINK_INSTT_CD','ko','I0000144','e제너두','e제너두',60,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','11000','시청','',1000,'Y','','','','');
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('LOCGOV_CODE','ko','11110','종로구',NULL,1001,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','11140','중구',NULL,1002,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','11170','용산구',NULL,1003,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','11200','성동구',NULL,1004,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','11215','광진구',NULL,1005,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','11230','동대문구',NULL,1006,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','11260','중랑구',NULL,1007,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','11290','성북구',NULL,1008,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','11305','강북구',NULL,1009,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','11320','도봉구',NULL,1010,'Y',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('LOCGOV_CODE','ko','11350','노원구',NULL,1011,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','11380','은평구',NULL,1012,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','11410','서대문구',NULL,1013,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','11440','마포구',NULL,1014,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','11470','양천구',NULL,1015,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','11500','강서구',NULL,1016,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','11530','구로구',NULL,1017,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','11545','금천구',NULL,1018,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','11560','영등포구',NULL,1019,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','11590','동작구',NULL,1020,'Y',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('LOCGOV_CODE','ko','11620','관악구',NULL,1021,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','11650','서초구',NULL,1022,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','11680','강남구',NULL,1023,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','11710','송파구',NULL,1024,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','11740','강동구',NULL,1025,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','12000','시청',NULL,2000,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','12110','목포시',NULL,2001,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','12130','여수시',NULL,2002,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','12150','순천시',NULL,2003,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','12170','나주시',NULL,2004,'Y',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('LOCGOV_CODE','ko','12190','광양시',NULL,2005,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','12210','동구',NULL,2006,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','12240','서구',NULL,2007,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','12270','남구',NULL,2008,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','12300','북구',NULL,2009,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','12330','광산구',NULL,2010,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','12710','담양군',NULL,2011,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','12720','곡성군',NULL,2012,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','12730','구례군',NULL,2013,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','12740','고흥군',NULL,2014,'Y',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('LOCGOV_CODE','ko','12750','보성군',NULL,2015,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','12760','화순군',NULL,2016,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','12770','장흥군',NULL,2017,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','12780','강진군',NULL,2018,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','12790','해남군',NULL,2019,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','12800','영암군',NULL,2020,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','12810','무안군',NULL,2021,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','12820','함평군',NULL,2022,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','12830','영광군',NULL,2023,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','12840','장성군',NULL,2024,'Y',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('LOCGOV_CODE','ko','12850','완도군',NULL,2025,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','12860','진도군',NULL,2026,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','12870','신안군',NULL,2027,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','26000','시청',NULL,3000,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','26110','중구',NULL,3001,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','26140','서구',NULL,3002,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','26170','동구',NULL,3003,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','26200','영도구',NULL,3004,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','26230','부산진구',NULL,3005,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','26260','동래구',NULL,3006,'Y',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('LOCGOV_CODE','ko','26290','남구',NULL,3007,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','26320','북구',NULL,3008,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','26350','해운대구',NULL,3009,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','26380','사하구',NULL,3010,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','26410','금정구',NULL,3011,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','26440','강서구',NULL,3012,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','26470','연제구',NULL,3013,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','26500','수영구',NULL,3014,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','26530','사상구',NULL,3015,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','26710','기장군',NULL,3016,'Y',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('LOCGOV_CODE','ko','27000','시청',NULL,4000,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','27110','중구',NULL,4001,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','27140','동구',NULL,4002,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','27170','서구',NULL,4003,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','27200','남구',NULL,4004,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','27230','북구',NULL,4005,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','27260','수성구',NULL,4006,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','27290','달서구',NULL,4007,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','27710','달성군',NULL,4008,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','27720','군위군','',4009,'Y','','','','');
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('LOCGOV_CODE','ko','28000','시청',NULL,5000,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','28110','중구',NULL,54,'N',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','28125','제물포구',NULL,5003,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','28140','동구',NULL,55,'N',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','28155','영종구',NULL,5004,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','28177','미추홀구',NULL,5005,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','28185','연수구',NULL,5006,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','28200','남동구',NULL,5007,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','28237','부평구',NULL,5008,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','28245','계양구',NULL,5009,'Y',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('LOCGOV_CODE','ko','28260','서구',NULL,61,'N',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','28275','서해구',NULL,5010,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','28290','검단구',NULL,5011,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','28710','강화군',NULL,5001,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','28720','옹진군',NULL,5002,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','30000','시청',NULL,6000,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','30110','동구',NULL,6001,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','30140','중구',NULL,6002,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','30170','서구',NULL,6003,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','30200','유성구',NULL,6004,'Y',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('LOCGOV_CODE','ko','30230','대덕구',NULL,6005,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','31000','시청',NULL,7000,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','31110','중구',NULL,7001,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','31140','남구',NULL,7002,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','31170','동구',NULL,7003,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','31200','북구',NULL,7004,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','31710','울주군',NULL,7005,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','36000','시청',NULL,8000,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','41000','도청',NULL,9000,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','41110','수원시',NULL,9001,'Y',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('LOCGOV_CODE','ko','41130','성남시',NULL,9002,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','41150','의정부시',NULL,9003,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','41170','안양시',NULL,9004,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','41190','부천시',NULL,9005,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','41210','광명시',NULL,9006,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','41220','평택시',NULL,9007,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','41250','동두천시',NULL,9008,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','41270','안산시',NULL,9009,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','41280','고양시',NULL,9010,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','41290','과천시',NULL,9011,'Y',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('LOCGOV_CODE','ko','41310','구리시',NULL,9012,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','41360','남양주시',NULL,9013,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','41370','오산시',NULL,9014,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','41390','시흥시',NULL,9015,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','41410','군포시',NULL,9016,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','41430','의왕시',NULL,9017,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','41450','하남시',NULL,9018,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','41460','용인시',NULL,9019,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','41480','파주시',NULL,9020,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','41500','이천시',NULL,9021,'Y',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('LOCGOV_CODE','ko','41550','안성시',NULL,9022,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','41570','김포시',NULL,9023,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','41590','화성시',NULL,9024,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','41610','광주시',NULL,9025,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','41630','양주시',NULL,9026,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','41650','포천시',NULL,9027,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','41670','여주시',NULL,9028,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','41800','연천군',NULL,9029,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','41820','가평군',NULL,9030,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','41830','양평군',NULL,9031,'Y',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('LOCGOV_CODE','ko','43000','도청',NULL,11000,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','43110','청주시',NULL,11001,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','43130','충주시',NULL,11002,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','43150','제천시',NULL,11003,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','43720','보은군',NULL,11004,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','43730','옥천군',NULL,11005,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','43740','영동군',NULL,11006,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','43745','증평군',NULL,11007,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','43750','진천군',NULL,11008,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','43760','괴산군',NULL,11009,'Y',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('LOCGOV_CODE','ko','43770','음성군',NULL,11010,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','43800','단양군',NULL,11011,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','44000','도청',NULL,12000,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','44130','천안시',NULL,12001,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','44150','공주시',NULL,12002,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','44180','보령시',NULL,12003,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','44200','아산시',NULL,12004,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','44210','서산시',NULL,12005,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','44230','논산시',NULL,12006,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','44250','계룡시',NULL,12007,'Y',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('LOCGOV_CODE','ko','44270','당진시','',12015,'Y','','','',''),
	 ('LOCGOV_CODE','ko','44710','금산군',NULL,12008,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','44760','부여군',NULL,12009,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','44770','서천군',NULL,12010,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','44790','청양군',NULL,12011,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','44800','홍성군',NULL,12012,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','44810','예산군',NULL,12013,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','44825','태안군',NULL,12014,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','46000','도청',NULL,177,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','47000','도청',NULL,14000,'Y',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('LOCGOV_CODE','ko','47110','포항시',NULL,14001,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','47130','경주시',NULL,14002,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','47150','김천시',NULL,14003,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','47170','안동시',NULL,14004,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','47190','구미시',NULL,14005,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','47210','영주시',NULL,14006,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','47230','영천시',NULL,14007,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','47250','상주시',NULL,14008,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','47280','문경시',NULL,14009,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','47290','경산시',NULL,14010,'Y',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('LOCGOV_CODE','ko','47730','의성군',NULL,14011,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','47750','청송군',NULL,14012,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','47760','영양군',NULL,14013,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','47770','영덕군',NULL,14014,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','47820','청도군',NULL,14015,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','47830','고령군',NULL,14016,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','47840','성주군',NULL,14017,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','47850','칠곡군',NULL,14018,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','47900','예천군',NULL,14019,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','47920','봉화군',NULL,14020,'Y',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('LOCGOV_CODE','ko','47930','울진군',NULL,14021,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','47940','울릉군',NULL,14022,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','48000','도청',NULL,15000,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','48120','창원시',NULL,15001,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','48170','진주시',NULL,15002,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','48220','통영시',NULL,15003,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','48240','사천시',NULL,15004,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','48250','김해시',NULL,15005,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','48270','밀양시',NULL,15006,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','48310','거제시',NULL,15007,'Y',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('LOCGOV_CODE','ko','48330','양산시',NULL,15008,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','48720','의령군',NULL,15009,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','48730','함안군',NULL,15010,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','48740','창녕군',NULL,15011,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','48820','고성군',NULL,15012,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','48840','남해군',NULL,15013,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','48850','하동군',NULL,15014,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','48860','산청군',NULL,15015,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','48870','함양군',NULL,15016,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','48880','거창군',NULL,15017,'Y',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('LOCGOV_CODE','ko','48890','합천군',NULL,15018,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','50000','도청',NULL,16000,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','50010','테스트','',260,'N','','','',''),
	 ('LOCGOV_CODE','ko','50020','등록테스트','',261,'N','','','',''),
	 ('LOCGOV_CODE','ko','51000','도청','',10000,'Y','','','',''),
	 ('LOCGOV_CODE','ko','51110','춘천시',NULL,10001,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','51130','원주시',NULL,10002,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','51150','강릉시',NULL,10003,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','51170','동해시',NULL,10004,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','51190','태백시',NULL,10005,'Y',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('LOCGOV_CODE','ko','51210','속초시',NULL,10006,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','51230','삼척시',NULL,10007,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','51720','홍천군',NULL,10008,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','51730','횡성군',NULL,10009,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','51750','영월군',NULL,10010,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','51760','평창군',NULL,10011,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','51770','정선군',NULL,10012,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','51780','철원군',NULL,10013,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','51790','화천군',NULL,10014,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','51800','양구군',NULL,10015,'Y',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('LOCGOV_CODE','ko','51810','인제군',NULL,10016,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','51820','고성군',NULL,10017,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','51830','양양군',NULL,10018,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','52000','도청','',13000,'Y','','','',''),
	 ('LOCGOV_CODE','ko','52110','전주시',NULL,13001,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','52130','군산시',NULL,13002,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','52140','익산시',NULL,13003,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','52180','정읍시',NULL,13004,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','52190','남원시',NULL,13005,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','52210','김제시',NULL,13006,'Y',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('LOCGOV_CODE','ko','52710','완주군',NULL,13007,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','52720','진안군',NULL,13008,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','52730','무주군',NULL,13009,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','52740','장수군',NULL,13010,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','52750','임실군',NULL,13011,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','52770','순창군',NULL,13012,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','52790','고창군',NULL,13013,'Y',NULL,NULL,NULL,NULL),
	 ('LOCGOV_CODE','ko','52800','부안군',NULL,13014,'Y',NULL,NULL,NULL,NULL),
	 ('LOGIN_PATH','ko','100','ID/PWD',NULL,1,'Y',NULL,NULL,NULL,NULL),
	 ('LOGIN_PATH','ko','200','간편인증',NULL,2,'Y',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('LOGIN_PATH','ko','300','디지털원패스',NULL,3,'Y',NULL,NULL,NULL,NULL),
	 ('LOGIN_PATH','ko','400','PKI',NULL,4,'Y',NULL,NULL,NULL,NULL),
	 ('LOGIN_PATH','ko','500','카카오인증',NULL,5,'Y',NULL,NULL,NULL,NULL),
	 ('LOGIN_PATH','ko','600','네이버인증',NULL,6,'Y',NULL,NULL,NULL,NULL),
	 ('LOGIN_PATH','ko','700','민간개방API',NULL,7,'Y',NULL,NULL,NULL,NULL),
	 ('MAIL_PWSEARCH','ko','comp_name','회사명',NULL,3,'Y',NULL,NULL,NULL,NULL),
	 ('MAIL_PWSEARCH','ko','find_id','찾은 ID',NULL,4,'Y',NULL,NULL,NULL,NULL),
	 ('MAIL_PWSEARCH','ko','find_pw','임시발급된 패스워드',NULL,5,'Y',NULL,NULL,NULL,NULL),
	 ('MAIL_PWSEARCH','ko','name','이름',NULL,1,'Y',NULL,NULL,NULL,NULL),
	 ('MAIL_PWSEARCH','ko','site_name','상점명',NULL,1,'Y',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('MAIL_PWSEARCH','ko','site_url','사이트URL',NULL,2,'Y',NULL,NULL,NULL,NULL),
	 ('MAIL_QNA_COMPLETE','ko','email','메일주소','null',3,'Y',NULL,NULL,NULL,NULL),
	 ('MAIL_QNA_COMPLETE','ko','item_name','상품명',NULL,5,'Y',NULL,NULL,NULL,NULL),
	 ('MAIL_QNA_COMPLETE','ko','order_code','주문번호',NULL,4,'Y',NULL,NULL,NULL,NULL),
	 ('MAIL_QNA_COMPLETE','ko','qna_group','문의그룹',NULL,6,'Y',NULL,NULL,NULL,NULL),
	 ('MAIL_QNA_COMPLETE','ko','qna_type','문의타입',NULL,7,'Y',NULL,NULL,NULL,NULL),
	 ('MAIL_QNA_COMPLETE','ko','question','문의내용',NULL,8,'Y',NULL,NULL,NULL,NULL),
	 ('MAIL_QNA_COMPLETE','ko','site_name','상점명',NULL,1,'Y',NULL,NULL,NULL,NULL),
	 ('MAIL_QNA_COMPLETE','ko','user_name','문의자이름',NULL,2,'Y',NULL,NULL,NULL,NULL),
	 ('MAINTEN_CATE_CODE','ko','1','기부','기부',1,'Y',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('MAINTEN_CATE_CODE','ko','2','답례품','답례품',2,'Y',NULL,NULL,NULL,NULL),
	 ('MAINTEN_CATE_CODE','ko','3','기타','기타',3,'Y',NULL,NULL,NULL,NULL),
	 ('MAINTEN_KI_CODE','ko','1','홈페이지','홈페이지',1,'Y',NULL,NULL,NULL,NULL),
	 ('MAINTEN_KI_CODE','ko','2','관리시스템','관리시스템',2,'Y',NULL,NULL,NULL,NULL),
	 ('MAINTEN_PATH_CODE','ko','1','소통방','소통방',1,'Y',NULL,NULL,NULL,NULL),
	 ('MAINTEN_PATH_CODE','ko','10','기타','기타',10,'Y',NULL,NULL,NULL,NULL),
	 ('MAINTEN_PATH_CODE','ko','2','회의','회의',2,'Y',NULL,NULL,NULL,NULL),
	 ('MAINTEN_PATH_CODE','ko','3','이메일','이메일',3,'Y',NULL,NULL,NULL,NULL),
	 ('MAINTEN_PATH_CODE','ko','4','SR게시판','SR게시판',4,'Y',NULL,NULL,NULL,NULL),
	 ('MAINTEN_PATH_CODE','ko','5','내부메신저','내부메신저',5,'Y',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('MAINTEN_PATH_CODE','ko','6','SNS','SNS',6,'Y',NULL,NULL,NULL,NULL),
	 ('MAINTEN_PATH_CODE','ko','7','전화','전화',7,'Y',NULL,NULL,NULL,NULL),
	 ('MAINTEN_PATH_CODE','ko','8','KLID','KLID',8,'Y',NULL,NULL,NULL,NULL),
	 ('MAINTEN_PATH_CODE','ko','9','사업장','사업장',9,'Y',NULL,NULL,NULL,NULL),
	 ('MAINTEN_PROC_CODE','ko','1','기능신규','기능신규',1,'Y',NULL,NULL,NULL,NULL),
	 ('MAINTEN_PROC_CODE','ko','2','기능개선','기능개선',2,'Y',NULL,NULL,NULL,NULL),
	 ('MAINTEN_PROC_CODE','ko','3','오류수정','오류수정',3,'Y',NULL,NULL,NULL,NULL),
	 ('MAINTEN_PROC_CODE','ko','4','자료추출','자료추출',4,'Y',NULL,NULL,NULL,NULL),
	 ('MAINTEN_PROC_CODE','ko','5','데이터수정','데이터수정',5,'Y',NULL,NULL,NULL,NULL),
	 ('MAINTEN_PROC_CODE','ko','6','기타','기타',6,'Y',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('MAINTEN_STATE_CODE','ko','1','접수','접수',1,'Y','','','',''),
	 ('MAINTEN_STATE_CODE','ko','2','처리중','처리중',2,'Y',NULL,NULL,NULL,NULL),
	 ('MAINTEN_STATE_CODE','ko','3','처리완료','처리완료',3,'Y',NULL,NULL,NULL,NULL),
	 ('MAINTEN_STATE_CODE','ko','9','제외','제외',9,'Y',NULL,NULL,NULL,NULL),
	 ('MAX_AMT_LIMIT','ko','2024','5000000','5,000,000',1,'Y','','','',''),
	 ('MAX_AMT_LIMIT','ko','2025','20000000','20,000,000',2,'Y','','','',''),
	 ('MAX_AMT_LIMIT','ko','2026','20000000','20,000,000',3,'Y','','','',''),
	 ('MAX_AMT_LIMIT','ko','2027','20000000','20,000,000',4,'Y','','','',''),
	 ('MAX_AMT_LIMIT','ko','2028','20000000','20,000,000',5,'Y','','','',''),
	 ('MAX_AMT_LIMIT','ko','2029','20000000','20,000,000',6,'Y','','','','');
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('MAX_AMT_LIMIT','ko','2030','20000000','20,000,000',7,'Y','','','',''),
	 ('MENU_URL','ko','001','/donation/guide1.html','고향사랑기부제안내',1,'Y','','','',''),
	 ('MENU_URL','ko','002','/donation/guide2.html','온라인 기부절차 안내',2,'Y','','','',''),
	 ('MENU_URL','ko','003','/donation/guide3.html','연말정산간편서비스안내',3,'Y','','','',''),
	 ('MENU_URL','ko','004','/donation/guide4.html','종합소득세 확정 서비스 안내',4,'Y','','','',''),
	 ('MENU_URL','ko','005','/donation/guide5.html','오프라인 기부절차 안내',5,'Y','','','',''),
	 ('MENU_URL','ko','006','/donation/guide6.html','고향사랑기부 주의사항',6,'Y','','','',''),
	 ('MENU_URL','ko','007','/donation/map-select.html','기부지자체선택 (지도)',7,'Y','','','',''),
	 ('MENU_URL','ko','008','/donation/list-select.html','기금사업 소개',8,'Y','','','',''),
	 ('MENU_URL','ko','009','/donation/donation.html','기부하기',9,'Y','','','','');
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('MENU_URL','ko','010','/donation/intro.html','기부하기-메인',10,'Y','','','',''),
	 ('MENU_URL','ko','011','/donation/process.html','기부하기-처리중',11,'Y','','','',''),
	 ('MENU_URL','ko','012','/mypage/cntrList.html','마이페이지 - 기부내역 현황',12,'Y','','','',''),
	 ('MENU_URL','ko','013','/mypage/cntrPoint.html','마이페이지 - 기부포인트 현황',13,'Y','','','',''),
	 ('MENU_URL','ko','014','/mypage/cntrPointDetail.html','마이페이지 - 기부포인트 현황:상세보기',14,'Y','','','',''),
	 ('MENU_URL','ko','015','/mypage/intrstLocGov.html','마이페이지 - 관심지자체',15,'Y','','','',''),
	 ('MENU_URL','ko','016','/users/secede.html','마이페이지-회원정보수정-회원탈퇴',16,'Y','','','',''),
	 ('MENU_URL','ko','017','/users/modify.html','마이페이지-회원정보수정',17,'Y','','','',''),
	 ('MENU_URL','ko','018','/notice/list.html','고객센터-공지사항',18,'Y','','','',''),
	 ('MENU_URL','ko','019','/data-board/list.html','고객센터 - 자료실 ',19,'Y','','','','');
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('MENU_URL','ko','020','/data-board/detail.html','고객센터 - 자료실 보기',20,'Y','','','',''),
	 ('MENU_URL','ko','021','/qna/qna-open.html','고객센터-Q&A',21,'Y','','','',''),
	 ('MENU_URL','ko','022','/qna/qna-detail.html','고객센터-Q&A 보기',22,'Y','','','',''),
	 ('MENU_URL','ko','023','/qna/qna-edit.html','고객센터-Q&A 수정하기',23,'Y','','','',''),
	 ('MENU_URL','ko','024','/qna/qna-form.html','고객센터-Q&A 글쓰기',24,'Y','','','',''),
	 ('MENU_URL','ko','025','/faq/list.html','고객센터-FAQ',25,'Y','','','',''),
	 ('MENU_URL','ko','026','/mypage/inquiry.html','고객센터-1:1 문의',26,'Y','','','',''),
	 ('MENU_URL','ko','027','/guide/help.html','고객센터-도움말',27,'Y','','','',''),
	 ('MENU_URL','ko','028','/guide/help-detail.html','고객센터-도움말 보기',28,'Y','','','',''),
	 ('MENU_URL','ko','029','/guide/sitemap.html','고객센터-사이트맵',29,'Y','','','','');
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('MENU_URL','ko','030','/users/onepass-join.html','디지털원패스 본인인증',30,'Y','','','',''),
	 ('MENU_URL','ko','031','/users/join.html','일반 회원 정보입력',31,'Y','','','',''),
	 ('MENU_URL','ko','032','/totalsearch/index.html','통합검색',32,'Y','','','',''),
	 ('MENU_URL','ko','033','/users/login.html','로그인',33,'Y','','','',''),
	 ('NICEPAY_BANK_LIST','ko','001','한국은행','한국은행',1,'N',NULL,NULL,NULL,NULL),
	 ('NICEPAY_BANK_LIST','ko','002','산업은행','산업은행',2,'N',NULL,NULL,NULL,NULL),
	 ('NICEPAY_BANK_LIST','ko','003','기업은행','기업은행',3,'Y',NULL,NULL,NULL,NULL),
	 ('NICEPAY_BANK_LIST','ko','004','국민은행','국민은행',4,'Y',NULL,NULL,NULL,NULL),
	 ('NICEPAY_BANK_LIST','ko','007','수협은행','수협은행',5,'Y',NULL,NULL,NULL,NULL),
	 ('NICEPAY_BANK_LIST','ko','008','수출입은행','수출입은행',6,'N',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('NICEPAY_BANK_LIST','ko','011','농협은행','농협은행',7,'Y',NULL,NULL,NULL,NULL),
	 ('NICEPAY_BANK_LIST','ko','012','지역 농축협','지역 농축협',8,'Y',NULL,NULL,NULL,NULL),
	 ('NICEPAY_BANK_LIST','ko','020','우리은행','우리은행',9,'Y',NULL,NULL,NULL,NULL),
	 ('NICEPAY_BANK_LIST','ko','023','SC제일은행','SC제일은행',10,'Y',NULL,NULL,NULL,NULL),
	 ('NICEPAY_BANK_LIST','ko','027','한국씨티은행','한국씨티은행',11,'Y',NULL,NULL,NULL,NULL),
	 ('NICEPAY_BANK_LIST','ko','031','대구은행','대구은행',12,'Y',NULL,NULL,NULL,NULL),
	 ('NICEPAY_BANK_LIST','ko','032','부산은행','부산은행',13,'Y',NULL,NULL,NULL,NULL),
	 ('NICEPAY_BANK_LIST','ko','034','광주은행','광주은행',14,'Y',NULL,NULL,NULL,NULL),
	 ('NICEPAY_BANK_LIST','ko','035','제주은행','제주은행',15,'Y',NULL,NULL,NULL,NULL),
	 ('NICEPAY_BANK_LIST','ko','037','전북은행','전북은행',16,'Y',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('NICEPAY_BANK_LIST','ko','039','경남은행','경남은행',17,'Y',NULL,NULL,NULL,NULL),
	 ('NICEPAY_BANK_LIST','ko','045','새마을금고중앙회','새마을금고중앙회',18,'Y',NULL,NULL,NULL,NULL),
	 ('NICEPAY_BANK_LIST','ko','048','신협','신협',19,'Y',NULL,NULL,NULL,NULL),
	 ('NICEPAY_BANK_LIST','ko','050','저축은행','저축은행',20,'N',NULL,NULL,NULL,NULL),
	 ('NICEPAY_BANK_LIST','ko','051','기타 외국계은행','기타 외국계은행',21,'N',NULL,NULL,NULL,NULL),
	 ('NICEPAY_BANK_LIST','ko','052','모건스탠리은행','모건스탠리은행',22,'N',NULL,NULL,NULL,NULL),
	 ('NICEPAY_BANK_LIST','ko','054','HSBC은행','HSBC은행',23,'N',NULL,NULL,NULL,NULL),
	 ('NICEPAY_BANK_LIST','ko','055','도이치은행','도이치은행',24,'N',NULL,NULL,NULL,NULL),
	 ('NICEPAY_BANK_LIST','ko','057','제이피모간체이스은행','제이피모간체이스은행',25,'N',NULL,NULL,NULL,NULL),
	 ('NICEPAY_BANK_LIST','ko','058','미즈호은행','미즈호은행',26,'N',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('NICEPAY_BANK_LIST','ko','059','엠유에프지은행','엠유에프지은행',27,'N',NULL,NULL,NULL,NULL),
	 ('NICEPAY_BANK_LIST','ko','060','BOA은행','BOA은행',28,'Y',NULL,NULL,NULL,NULL),
	 ('NICEPAY_BANK_LIST','ko','061','비엔피파리은행','비엔피파리은행',29,'N',NULL,NULL,NULL,NULL),
	 ('NICEPAY_BANK_LIST','ko','062','중국공상은행','중국공상은행',30,'N',NULL,NULL,NULL,NULL),
	 ('NICEPAY_BANK_LIST','ko','063','중국은행','중국은행',31,'N',NULL,NULL,NULL,NULL),
	 ('NICEPAY_BANK_LIST','ko','064','산림조합중앙회','산림조합중앙회',32,'N',NULL,NULL,NULL,NULL),
	 ('NICEPAY_BANK_LIST','ko','065','대화은행','대화은행',33,'N',NULL,NULL,NULL,NULL),
	 ('NICEPAY_BANK_LIST','ko','066','교통은행','교통은행',34,'N',NULL,NULL,NULL,NULL),
	 ('NICEPAY_BANK_LIST','ko','067','중국건설은행','중국건설은행',35,'N',NULL,NULL,NULL,NULL),
	 ('NICEPAY_BANK_LIST','ko','071','우체국','우체국',36,'Y',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('NICEPAY_BANK_LIST','ko','076','신용보증기금','신용보증기금',37,'N',NULL,NULL,NULL,NULL),
	 ('NICEPAY_BANK_LIST','ko','077','기술보증기금','기술보증기금',38,'N',NULL,NULL,NULL,NULL),
	 ('NICEPAY_BANK_LIST','ko','081','하나은행','하나은행',39,'Y',NULL,NULL,NULL,NULL),
	 ('NICEPAY_BANK_LIST','ko','088','신한은행','신한은행',40,'Y',NULL,NULL,NULL,NULL),
	 ('NICEPAY_BANK_LIST','ko','089','케이뱅크','케이뱅크',41,'Y',NULL,NULL,NULL,NULL),
	 ('NICEPAY_BANK_LIST','ko','090','카카오뱅크','카카오뱅크',42,'Y',NULL,NULL,NULL,NULL),
	 ('NICEPAY_BANK_LIST','ko','091','국세청','국세청',43,'N',NULL,NULL,NULL,NULL),
	 ('NICEPAY_BANK_LIST','ko','093','한국주택금융공사','한국주택금융공사',44,'N',NULL,NULL,NULL,NULL),
	 ('NICEPAY_BANK_LIST','ko','094','서울보증보험','서울보증보험',45,'N',NULL,NULL,NULL,NULL),
	 ('NICEPAY_BANK_LIST','ko','095','경찰청','경찰청',46,'N',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('NICEPAY_BANK_LIST','ko','096','한국전자금융(주)','한국전자금융(주)',47,'N',NULL,NULL,NULL,NULL),
	 ('NICEPAY_BANK_LIST','ko','099','금융결제원','금융결제원',48,'N',NULL,NULL,NULL,NULL),
	 ('NICEPAY_BANK_LIST','ko','101','한국신용정보원','한국신용정보원',49,'N',NULL,NULL,NULL,NULL),
	 ('NICEPAY_BANK_LIST','ko','102','대신저축은행','대신저축은행',50,'N',NULL,NULL,NULL,NULL),
	 ('NICEPAY_BANK_LIST','ko','103','에스비아이저축은행','에스비아이저축은행',51,'N',NULL,NULL,NULL,NULL),
	 ('NICEPAY_BANK_LIST','ko','104','에이치케이저축은행','에이치케이저축은행',52,'N',NULL,NULL,NULL,NULL),
	 ('NICEPAY_BANK_LIST','ko','105','웰컴저축은행','웰컴저축은행',53,'N',NULL,NULL,NULL,NULL),
	 ('NICEPAY_BANK_LIST','ko','209','유안타증권(동양종합금융증권)','유안타증권(동양종합금융증권)',54,'N',NULL,NULL,NULL,NULL),
	 ('NICEPAY_BANK_LIST','ko','218','KB증권','KB증권',55,'N',NULL,NULL,NULL,NULL),
	 ('NICEPAY_BANK_LIST','ko','221','골든브릿지투자증권','골든브릿지투자증권',56,'N',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('NICEPAY_BANK_LIST','ko','222','한양증권','한양증권',57,'N',NULL,NULL,NULL,NULL),
	 ('NICEPAY_BANK_LIST','ko','223','리딩투자증권','리딩투자증권',58,'N',NULL,NULL,NULL,NULL),
	 ('NICEPAY_BANK_LIST','ko','224','BNK투자증권','BNK투자증권',59,'N',NULL,NULL,NULL,NULL),
	 ('NICEPAY_BANK_LIST','ko','225','IBK투자증권','IBK투자증권',60,'N',NULL,NULL,NULL,NULL),
	 ('NICEPAY_BANK_LIST','ko','227','KTB투자증권','KTB투자증권',61,'N',NULL,NULL,NULL,NULL),
	 ('NICEPAY_BANK_LIST','ko','238','미래에셋대우','미래에셋대우',62,'N',NULL,NULL,NULL,NULL),
	 ('NICEPAY_BANK_LIST','ko','240','삼성증권','삼성증권',63,'N',NULL,NULL,NULL,NULL),
	 ('NICEPAY_BANK_LIST','ko','243','한국투자증권','한국투자증권',64,'N',NULL,NULL,NULL,NULL),
	 ('NICEPAY_BANK_LIST','ko','247','NH투자증권','NH투자증권',65,'N',NULL,NULL,NULL,NULL),
	 ('NICEPAY_BANK_LIST','ko','261','교보증권','교보증권',66,'N',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('NICEPAY_BANK_LIST','ko','262','하이투자증권','하이투자증권',67,'N',NULL,NULL,NULL,NULL),
	 ('NICEPAY_BANK_LIST','ko','263','현대차증권','현대차증권',68,'N',NULL,NULL,NULL,NULL),
	 ('NICEPAY_BANK_LIST','ko','264','키움증권','키움증권',69,'N',NULL,NULL,NULL,NULL),
	 ('NICEPAY_BANK_LIST','ko','265','이베스트투자증권','이베스트투자증권',70,'N',NULL,NULL,NULL,NULL),
	 ('NICEPAY_BANK_LIST','ko','266','SK증권','SK증권',71,'N',NULL,NULL,NULL,NULL),
	 ('NICEPAY_BANK_LIST','ko','267','대신증권','대신증권',72,'N',NULL,NULL,NULL,NULL),
	 ('NICEPAY_BANK_LIST','ko','269','한화투자증권','한화투자증권',73,'N',NULL,NULL,NULL,NULL),
	 ('NICEPAY_BANK_LIST','ko','270','하나금융투자','하나금융투자',74,'N',NULL,NULL,NULL,NULL),
	 ('NICEPAY_BANK_LIST','ko','278','신한금융투자','신한금융투자',75,'N',NULL,NULL,NULL,NULL),
	 ('NICEPAY_BANK_LIST','ko','279','DB금융투자','DB금융투자',76,'N',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('NICEPAY_BANK_LIST','ko','280','유진투자증권','유진투자증권',77,'N',NULL,NULL,NULL,NULL),
	 ('NICEPAY_BANK_LIST','ko','287','메리츠종합금융증권','메리츠종합금융증권',78,'N',NULL,NULL,NULL,NULL),
	 ('NICEPAY_BANK_LIST','ko','289','NH투자증권','NH투자증권',79,'N',NULL,NULL,NULL,NULL),
	 ('NICEPAY_BANK_LIST','ko','290','부국증권','부국증권',80,'N',NULL,NULL,NULL,NULL),
	 ('NICEPAY_BANK_LIST','ko','291','신영증권','신영증권',81,'N',NULL,NULL,NULL,NULL),
	 ('NICEPAY_BANK_LIST','ko','292','케이프투자증권','케이프투자증권',82,'N',NULL,NULL,NULL,NULL),
	 ('NICEPAY_BANK_LIST','ko','293','한국증권금융','한국증권금융',83,'N',NULL,NULL,NULL,NULL),
	 ('NICEPAY_BANK_LIST','ko','294','펀드온라인코리아','펀드온라인코리아',84,'N',NULL,NULL,NULL,NULL),
	 ('NICEPAY_BANK_LIST','ko','295','우리종합금융','우리종합금융',85,'N',NULL,NULL,NULL,NULL),
	 ('NICEPAY_BANK_LIST','ko','299','아주캐피탈','아주캐피탈',86,'N',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('NTS_CODE','ko','01','등록',NULL,1,'Y',NULL,NULL,NULL,NULL),
	 ('NTS_CODE','ko','02','변경','',2,'Y','','','',''),
	 ('NTS_CODE','ko','03','과오납','',3,'Y','','','',''),
	 ('OFF_BANK_LIST','ko','011','농협은행','',1,'Y','','','',''),
	 ('OFF_BANK_LIST','ko','012','농축협',NULL,2,'Y',NULL,NULL,NULL,NULL),
	 ('OFF_BANK_LIST','ko','035','제주은행','',3,'Y','','','',''),
	 ('ORDER_PAY_TYPE','ko','ars','ARS',NULL,5,'N',NULL,NULL,NULL,NULL),
	 ('ORDER_PAY_TYPE','ko','bank','은행 입금',NULL,4,'Y',NULL,NULL,NULL,NULL),
	 ('ORDER_PAY_TYPE','ko','card','신용카드',NULL,1,'Y',NULL,NULL,NULL,NULL),
	 ('ORDER_PAY_TYPE','ko','card-write','수기결제',NULL,7,'N',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('ORDER_PAY_TYPE','ko','cash','현금',NULL,7,'Y',NULL,NULL,NULL,NULL),
	 ('ORDER_PAY_TYPE','ko','conv','편의점',NULL,3,'N',NULL,NULL,NULL,NULL),
	 ('ORDER_PAY_TYPE','ko','dlv','대금상환',NULL,2,'N',NULL,NULL,NULL,NULL),
	 ('ORDER_PAY_TYPE','ko','escrow','에스크로','',NULL,'Y','','','',''),
	 ('ORDER_PAY_TYPE','ko','give-point','기부포인트','기부포인트',10,'Y','','','',''),
	 ('ORDER_PAY_TYPE','ko','hp','휴대전화',NULL,NULL,'Y',NULL,NULL,NULL,NULL),
	 ('ORDER_PAY_TYPE','ko','kakaopay','카카오페이',NULL,NULL,'Y',NULL,NULL,NULL,NULL),
	 ('ORDER_PAY_TYPE','ko','naverpay','네이버페이',NULL,NULL,'Y',NULL,NULL,NULL,NULL),
	 ('ORDER_PAY_TYPE','ko','payco','PAYCO 간편결제',NULL,NULL,'Y',NULL,NULL,NULL,NULL),
	 ('ORDER_PAY_TYPE','ko','point','포인트',NULL,NULL,'Y',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('ORDER_PAY_TYPE','ko','realtimebank','실시간 계좌이체',NULL,NULL,'Y',NULL,NULL,NULL,NULL),
	 ('ORDER_PAY_TYPE','ko','vbank','가상계좌',NULL,6,'Y',NULL,NULL,NULL,NULL),
	 ('ORDER_STATUS','ko','0','입금대기',NULL,1,'Y',NULL,NULL,NULL,NULL),
	 ('ORDER_STATUS','ko','10','결제완료',NULL,2,'Y',NULL,NULL,NULL,NULL),
	 ('ORDER_STATUS','ko','20','배송준비중',NULL,3,'Y',NULL,NULL,NULL,NULL),
	 ('ORDER_STATUS','ko','30','배송중',NULL,4,'Y',NULL,NULL,NULL,NULL),
	 ('ORDER_STATUS','ko','35','배송(발송)완료','',5,'Y','','','',''),
	 ('ORDER_STATUS','ko','40','구매확정',NULL,6,'Y',NULL,NULL,NULL,NULL),
	 ('ORDER_STATUS','ko','50','교환처리중','',7,'Y','','','',''),
	 ('ORDER_STATUS','ko','55','교환배송중','',8,'Y','','','','');
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('ORDER_STATUS','ko','58','교환배송완료',NULL,9,'Y',NULL,NULL,NULL,NULL),
	 ('ORDER_STATUS','ko','59','교환거절','',10,'Y','','','',''),
	 ('ORDER_STATUS','ko','60','반품처리중','',11,'Y','','','',''),
	 ('ORDER_STATUS','ko','65','반품(환불)완료','',12,'Y','','','',''),
	 ('ORDER_STATUS','ko','69','반품거절','',13,'Y','','','',''),
	 ('ORDER_STATUS','ko','70','취소처리중','',14,'Y','','','',''),
	 ('ORDER_STATUS','ko','75','취소완료','',15,'Y','','','',''),
	 ('ORDER_STATUS','ko','90','주문취소요청',NULL,7,'N',NULL,NULL,NULL,NULL),
	 ('ORDER_STATUS','ko','95','취소승인 대기',NULL,8,'N',NULL,NULL,NULL,NULL),
	 ('ORDER_STATUS','ko','98','주문취소완료',NULL,9,'N',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('ORDER_STATUS','ko','99','주문취소완료',NULL,10,'N',NULL,NULL,NULL,NULL),
	 ('PHONE','ko','010','010','010',1,'Y',NULL,NULL,NULL,NULL),
	 ('PHONE','ko','011','011','011',2,'Y',NULL,NULL,NULL,NULL),
	 ('PHONE','ko','017','017','017',3,'Y',NULL,NULL,NULL,NULL),
	 ('PHONE','ko','019','019','019',4,'Y',NULL,NULL,NULL,NULL),
	 ('POLICY','ko','0','약관','',1,'Y',NULL,NULL,NULL,NULL),
	 ('POLICY','ko','1','개인정보처리방침','',2,'Y',NULL,NULL,NULL,NULL),
	 ('POLICY','ko','4','개인정보수집제3자동의','',3,'Y',NULL,NULL,NULL,NULL),
	 ('POLICY','ko','5','저작권정책','',4,'Y',NULL,NULL,NULL,NULL),
	 ('POLICY','ko','6','개인정보 수집·이용 동의','',5,'Y','','','','');
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('POP_ADMIN','ko','period','20260728172026081623','9990',1,'Y',NULL,NULL,NULL,NULL),
	 ('POP_ADMIN','ko','period2','20260803092026081323','9991',1,'Y',NULL,NULL,NULL,NULL),
	 ('PRJ_STATUS','ko','1','대기','지정기부 대기',1,'Y','','','',''),
	 ('PRJ_STATUS','ko','2','진행중','모금 진행중',2,'Y',NULL,NULL,'FRONT',NULL),
	 ('PRJ_STATUS','ko','9','종료','모금 종료',3,'Y',NULL,NULL,'FRONT',NULL),
	 ('QNA_GROUPS','ko','1','회원가입 문의','',1,'Y','','','locgov',''),
	 ('QNA_GROUPS','ko','10','배송 문의','',10,'Y','','','item',''),
	 ('QNA_GROUPS','ko','11','교환/반품/취소 문의','',11,'Y','','','item',''),
	 ('QNA_GROUPS','ko','12','시스템 개선 문의','',12,'Y','','','locgov',''),
	 ('QNA_GROUPS','ko','13','시스템 장애/에러','',13,'Y','','','locgov','');
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('QNA_GROUPS','ko','14','기타 문의','',14,'Y','','','item,locgov',''),
	 ('QNA_GROUPS','ko','2','로그인 문의','',2,'Y','','','locgov',''),
	 ('QNA_GROUPS','ko','3','기타 회원 문의','',3,'Y','','','',''),
	 ('QNA_GROUPS','ko','4','기부방법 문의','',4,'Y','','','',''),
	 ('QNA_GROUPS','ko','5','세액공제 문의','',5,'Y','','','',''),
	 ('QNA_GROUPS','ko','6','기타 기부 문의','',6,'Y','','','',''),
	 ('QNA_GROUPS','ko','7','기부포인트 문의','',7,'Y','','','',''),
	 ('QNA_GROUPS','ko','8','답례품 문의','',8,'Y','','','item',''),
	 ('QNA_GROUPS','ko','9','주문/결제 문의','',9,'Y','','','item',''),
	 ('QNA_GROUP_1','ko','1','주문 내용·배송·지불 등의 확인','1',1,'Y',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('QNA_GROUP_1','ko','10','기타','1',10,'Y',NULL,NULL,NULL,NULL),
	 ('QNA_GROUP_1','ko','2','구입상품 결함의 신고(손상, 먼지, 부품 부족 등)','1',2,'Y',NULL,NULL,NULL,NULL),
	 ('QNA_GROUP_1','ko','3','배송일, 배송지 변경','1',3,'Y',NULL,NULL,NULL,NULL),
	 ('QNA_GROUP_1','ko','4','지불 방법의 변경','1',4,'Y',NULL,NULL,NULL,NULL),
	 ('QNA_GROUP_1','ko','5','영수증의 발행·변경','1',5,'Y',NULL,NULL,NULL,NULL),
	 ('QNA_GROUP_1','ko','6','입금 확인, 입금 완료의 연락','1',6,'Y',NULL,NULL,NULL,NULL),
	 ('QNA_GROUP_1','ko','7','편의점 지불에 대해','1',7,'Y',NULL,NULL,NULL,NULL),
	 ('QNA_GROUP_1','ko','8','상품의 추가·변경·취소','1',8,'Y',NULL,NULL,NULL,NULL),
	 ('QNA_GROUP_1','ko','9','반품·교환(고객의 형편에 의한)','1',9,'Y',NULL,NULL,NULL,NULL),
	 ('QNA_GROUP_2','ko','1','자세한 설명, 사용 방법, 사양(사이즈) 등의 문의','2',11,'Y',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('QNA_GROUP_2','ko','2','보증·에프터 서비스·수리 문의','2',12,'Y',NULL,NULL,NULL,NULL),
	 ('QNA_GROUP_2','ko','3','입하·재고의 문의','2',13,'Y',NULL,NULL,NULL,NULL),
	 ('QNA_GROUP_2','ko','4','상품에 대한 의견과 요망','2',14,'Y',NULL,NULL,NULL,NULL),
	 ('QNA_GROUP_2','ko','5','기타','2',15,'Y',NULL,NULL,NULL,NULL),
	 ('QNA_GROUP_3','ko','1','ID·패스워드 문의','3',16,'Y',NULL,NULL,NULL,NULL),
	 ('QNA_GROUP_3','ko','2','주소·TEL·메일 주소등의 변경','3',17,'Y',NULL,NULL,NULL,NULL),
	 ('QNA_GROUP_3','ko','3','회원 등록·해제에 대해','3',18,'Y',NULL,NULL,NULL,NULL),
	 ('QNA_GROUP_3','ko','4','포인트 이용·확인 내용','3',19,'Y',NULL,NULL,NULL,NULL),
	 ('QNA_GROUP_3','ko','5','메일 매거진 수신 거부에 대해','3',20,'Y',NULL,NULL,NULL,NULL),
	 ('QNA_GROUP_3','ko','6','기타','3',21,'Y',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('QNA_GROUP_4','ko','1','카탈로그 송부 의뢰 정지','4',22,'Y',NULL,NULL,NULL,NULL),
	 ('QNA_GROUP_4','ko','2','저장소에 대한 문의','4',23,'Y',NULL,NULL,NULL,NULL),
	 ('QNA_GROUP_4','ko','3','강습회에 관한 문의','4',24,'Y',NULL,NULL,NULL,NULL),
	 ('QNA_GROUP_4','ko','4','기타','4',25,'Y',NULL,NULL,NULL,NULL),
	 ('QNA_GROUP_5','ko','1','로그인 주문 수속 등의 오류에 대한 문의','5',26,'Y',NULL,NULL,NULL,NULL),
	 ('QNA_GROUP_5','ko','2','기타','5',27,'Y',NULL,NULL,NULL,NULL),
	 ('QNA_GROUP_6','ko','1','우리 사장의 의견과 요망을 들려주세요','6',28,'Y',NULL,NULL,NULL,NULL),
	 ('RELAY_TYPE','ko','100','서울세외 부과','연계로그',1,'Y',NULL,NULL,NULL,NULL),
	 ('RELAY_TYPE','ko','101','서울세외 수납','연계로그',2,'Y',NULL,NULL,NULL,NULL),
	 ('RELAY_TYPE','ko','200','지방세외 부과','연계로그',3,'Y',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('RELAY_TYPE','ko','201','지방세외 수납','연계로그',4,'Y',NULL,NULL,NULL,NULL),
	 ('REMITTANCE_STATUS','ko','1','정산예정','구매자 구매확정시 설정됨',1,'Y',NULL,NULL,NULL,NULL),
	 ('REMITTANCE_STATUS','ko','3','정산확정','지자체관리자 정산확정시 설정됨',2,'Y',NULL,NULL,NULL,NULL),
	 ('REMITTANCE_STATUS','ko','4','정산확인','판매자 정산확인시 설정됨',3,'Y',NULL,NULL,NULL,NULL),
	 ('REMITTANCE_STATUS','ko','5','지급완료','지자체관리자 지급처리시 설정됨',4,'Y',NULL,NULL,NULL,NULL),
	 ('REMITTANCE_STATUS','ko','9','정산마감','판매자 입금확인시 설정됨',5,'Y',NULL,NULL,NULL,NULL),
	 ('REMITTANCE_TYPE','ko','1','일정산','일정산',NULL,'Y',NULL,NULL,NULL,NULL),
	 ('REMITTANCE_TYPE','ko','2','주정산','주정산',NULL,'Y',NULL,NULL,NULL,NULL),
	 ('REMITTANCE_TYPE','ko','3','15일정산','15일정산',NULL,'Y',NULL,NULL,NULL,NULL),
	 ('REMITTANCE_TYPE','ko','4','월정산','월정산',NULL,'Y',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('REQST_SE_CODE','ko','ROLE_ADMIN_10','지정기부','',5,'N','','','LCLGV',''),
	 ('REQST_SE_CODE','ko','ROLE_ADMIN_11','행정복지센터','',6,'N','','','LCLGV',''),
	 ('REQST_SE_CODE','ko','ROLE_ADMIN_2','시스템',NULL,4,'Y',NULL,NULL,'SYSTEM',NULL),
	 ('REQST_SE_CODE','ko','ROLE_ADMIN_4','행정안전부','',3,'Y','','','SYSTEM',''),
	 ('REQST_SE_CODE','ko','ROLE_ADMIN_6','지자체',NULL,1,'Y',NULL,NULL,'SYSTEM',NULL),
	 ('REQST_SE_CODE','ko','ROLE_ADMIN_8','오프라인',NULL,2,'Y',NULL,NULL,'SYSTEM',NULL),
	 ('REQ_STATUS','ko','100','요청','변경신청 요청',1,'Y',NULL,NULL,NULL,NULL),
	 ('REQ_STATUS','ko','200','취소','변경신청 취소',2,'Y',NULL,NULL,NULL,NULL),
	 ('REQ_STATUS','ko','999','승인','변경신청 승인',3,'Y',NULL,NULL,NULL,NULL),
	 ('RETURN_REASON','ko','1','상품이 잘못 배송됨','1',NULL,'Y',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('RETURN_REASON','ko','2','구매의사 취소','2',NULL,'Y',NULL,NULL,NULL,NULL),
	 ('RETURN_REASON','ko','3','상품 파손','1',NULL,'Y',NULL,NULL,NULL,NULL),
	 ('RETURN_REASON','ko','4','기타','2',NULL,'Y',NULL,NULL,NULL,NULL),
	 ('RETURN_REASON','ko','5','기타','2',NULL,'N',NULL,NULL,NULL,NULL),
	 ('RTNPSNT_REQST','ko','100','답례품을 제공 받음','O',1,'Y','','','',''),
	 ('RTNPSNT_REQST','ko','200','이번 고향사랑 기부금은 이월함',NULL,2,'Y',NULL,NULL,NULL,NULL),
	 ('RTNPSNT_REQST','ko','300','답례품을 제공받지 않음','X',3,'Y',NULL,NULL,NULL,NULL),
	 ('SBSCRB_SE','ko','100','온라인',NULL,1,'Y',NULL,NULL,NULL,NULL),
	 ('SBSCRB_SE','ko','200','오프라인',NULL,2,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','01','우체국택배',NULL,1,'Y',NULL,NULL,NULL,'3');
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('SMART_DELIVERY_COMPANY','ko','04','CJ대한통운',NULL,2,'Y',NULL,NULL,NULL,'2'),
	 ('SMART_DELIVERY_COMPANY','ko','05','한진택배',NULL,3,'Y',NULL,NULL,NULL,'4'),
	 ('SMART_DELIVERY_COMPANY','ko','06','로젠택배',NULL,4,'Y',NULL,NULL,NULL,'6'),
	 ('SMART_DELIVERY_COMPANY','ko','08','롯데택배',NULL,5,'Y',NULL,NULL,NULL,'5'),
	 ('SMART_DELIVERY_COMPANY','ko','100','나은물류',NULL,65,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','101','한샘서비스',NULL,66,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','102','SHIPNERGY',NULL,67,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','104','도도플렉스(dodoflex)',NULL,68,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','105','브릿지로지스㈜',NULL,69,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','107','LG전자',NULL,70,'Y',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('SMART_DELIVERY_COMPANY','ko','108','MEXGLOBAL',NULL,71,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','11','일양로지스',NULL,6,'Y',NULL,NULL,NULL,'12'),
	 ('SMART_DELIVERY_COMPANY','ko','112','1004홈',NULL,72,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','113','썬더히어로',NULL,73,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','114','캐나다쉬핑',NULL,74,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','117','YUNDA EXPRESS',NULL,75,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','118','롯데칠성',NULL,76,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','119','핑퐁',NULL,77,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','12','EMS',NULL,7,'Y',NULL,NULL,NULL,'16'),
	 ('SMART_DELIVERY_COMPANY','ko','120','발렉스 특수물류',NULL,78,'Y',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('SMART_DELIVERY_COMPANY','ko','121','바바바(bababa)',NULL,79,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','122','BAIMA EXPRESS',NULL,80,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','123','엔티엘피스',NULL,81,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','124','LTL',NULL,82,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','125','지케이글로벌',NULL,83,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','127','로지스팟',NULL,84,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','128','판월드로지스틱',NULL,85,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','129','홈픽 오늘도착',NULL,86,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','13','DHL',NULL,8,'Y',NULL,NULL,NULL,'17'),
	 ('SMART_DELIVERY_COMPANY','ko','130','로지스파트너',NULL,87,'Y',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('SMART_DELIVERY_COMPANY','ko','131','딜리래빗',NULL,88,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','132','지오피',NULL,89,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','134','에이치케이홀딩스',NULL,90,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','135','HTNS',NULL,91,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','136','케이제이티',NULL,92,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','137','더바오',NULL,93,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','138','라스트마일',NULL,94,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','14','UPS',NULL,9,'Y',NULL,NULL,NULL,'19'),
	 ('SMART_DELIVERY_COMPANY','ko','140','직구문',NULL,95,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','141','인터로지스',NULL,96,'Y',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('SMART_DELIVERY_COMPANY','ko','142','탱고앤고',NULL,97,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','143','투데이',NULL,98,'Y',NULL,NULL,NULL,'2000101'),
	 ('SMART_DELIVERY_COMPANY','ko','144','큐브플로우(CUBEFLOW)',NULL,99,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','145','현대글로비스',NULL,100,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','146','국제로지스틱(KSE)',NULL,101,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','147','에스더쉬핑',NULL,102,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','148','ARGO(테크타카)',NULL,103,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','149','골드스넵스',NULL,104,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','151','자이언트',NULL,105,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','152','엠티인터내셔널',NULL,106,'Y',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('SMART_DELIVERY_COMPANY','ko','153','이지로지스틱',NULL,107,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','154','케이티익스프레스',NULL,108,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','155','HY',NULL,109,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','156','유피로지스(제주)',NULL,110,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','157','반얀로지스틱스',NULL,111,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','158','AusPost',NULL,112,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','159','삼다수 가정배송',NULL,113,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','16','한의사랑택배',NULL,10,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','160','와이드테크',NULL,114,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','162','SAP EXPRESS',NULL,115,'Y',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('SMART_DELIVERY_COMPANY','ko','163','위니온',NULL,116,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','165','서림특송',NULL,117,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','166','Rincos',NULL,118,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','167','딜리박스',NULL,119,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','168','이스트라',NULL,120,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','169','JNT',NULL,121,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','17','천일택배',NULL,11,'Y',NULL,NULL,NULL,'15'),
	 ('SMART_DELIVERY_COMPANY','ko','170','유피로지스',NULL,122,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','171','올인닷컴',NULL,123,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','173','물류대장(택배)',NULL,124,'Y',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('SMART_DELIVERY_COMPANY','ko','175','풀무원샘물㈜',NULL,125,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','177','티에스지로지스',NULL,126,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','179','SLO(모든)',NULL,127,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','18','건영택배',NULL,12,'Y',NULL,NULL,NULL,'14'),
	 ('SMART_DELIVERY_COMPANY','ko','182','지씨에스',NULL,128,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','183','바로스',NULL,129,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','185','윤익스프레스(YunExpress)',NULL,130,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','186','레터스',NULL,131,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','187','벤더피아',NULL,132,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','188','CXCExpress',NULL,133,'Y',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('SMART_DELIVERY_COMPANY','ko','189','세븐일레븐 착한택배',NULL,134,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','190','물류대장(설치)',NULL,135,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','20','한진택배B2B',NULL,13,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','21','Fedex',NULL,14,'Y',NULL,NULL,NULL,'20'),
	 ('SMART_DELIVERY_COMPANY','ko','22','대신택배',NULL,15,'Y',NULL,NULL,NULL,'30'),
	 ('SMART_DELIVERY_COMPANY','ko','23','경동택배',NULL,16,'Y',NULL,NULL,NULL,'10'),
	 ('SMART_DELIVERY_COMPANY','ko','24','GS Postbox 택배',NULL,17,'Y',NULL,NULL,NULL,'8'),
	 ('SMART_DELIVERY_COMPANY','ko','25','TNT Express',NULL,18,'Y',NULL,NULL,NULL,'18'),
	 ('SMART_DELIVERY_COMPANY','ko','26','USPS',NULL,19,'Y',NULL,NULL,NULL,'21'),
	 ('SMART_DELIVERY_COMPANY','ko','28','GSMNtoN',NULL,20,'Y',NULL,NULL,NULL,'25');
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('SMART_DELIVERY_COMPANY','ko','30','KGL네트웍스',NULL,21,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','32','합동택배',NULL,22,'Y',NULL,NULL,NULL,'28'),
	 ('SMART_DELIVERY_COMPANY','ko','37','LX판토스',NULL,23,'Y',NULL,NULL,NULL,'24'),
	 ('SMART_DELIVERY_COMPANY','ko','38','ECMS Express',NULL,24,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','41','GSI Express',NULL,25,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','42','CJ대한통운 국제특송',NULL,26,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','43','애니트랙',NULL,27,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','44','SLX택배',NULL,28,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','45','우리택배(구호남택배)',NULL,29,'Y',NULL,NULL,NULL,'26'),
	 ('SMART_DELIVERY_COMPANY','ko','46','CU편의점택배',NULL,30,'Y',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('SMART_DELIVERY_COMPANY','ko','47','우리한방택배',NULL,31,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','48','ACI Express',NULL,32,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','49','A.C.E EXPRESS INC',NULL,33,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','50','GPS Logix',NULL,34,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','51','성원글로벌카고',NULL,35,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','53','농협택배',NULL,36,'Y',NULL,NULL,NULL,'27'),
	 ('SMART_DELIVERY_COMPANY','ko','54','홈픽택배',NULL,37,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','55','EuroParcel',NULL,38,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','60','YJS글로벌(영국)',NULL,39,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','63','은하쉬핑',NULL,40,'Y',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('SMART_DELIVERY_COMPANY','ko','65','YJS글로벌(월드)',NULL,41,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','66','Giant Network Group',NULL,42,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','69','대림통운',NULL,43,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','70','LOTOS CORPORATION',NULL,44,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','71','IK물류',NULL,45,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','72','성훈물류',NULL,46,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','73','CR로지텍',NULL,47,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','74','용마로지스',NULL,48,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','75','원더스퀵',NULL,49,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','77','LineExpress',NULL,50,'Y',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('SMART_DELIVERY_COMPANY','ko','81','제니엘시스템',NULL,51,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','82','컬리넥스트마일',NULL,52,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','84','스마트로지스',NULL,53,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','85','풀앳홈',NULL,54,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','87','이투마스(ETOMARS)',NULL,55,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','89','두발히어로',NULL,56,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','90','위니아딤채',NULL,57,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','91','하이브시티',NULL,58,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','92','지니고 당일배송',NULL,59,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','93','팬스타국제특송(PIEX)',NULL,60,'Y',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('SMART_DELIVERY_COMPANY','ko','94','카카오 T 당일배송',NULL,61,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','95','트랙스로지스',NULL,62,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','97','에이씨티앤코아물류',NULL,63,'Y',NULL,NULL,NULL,NULL),
	 ('SMART_DELIVERY_COMPANY','ko','99','롯데택배 해외특송',NULL,64,'Y',NULL,NULL,NULL,NULL),
	 ('TEL','ko','010','010','010',NULL,'Y','','','',''),
	 ('TEL','ko','02','02','02',NULL,'Y','','','',''),
	 ('TEL','ko','031','031','031',NULL,'Y',NULL,NULL,NULL,NULL),
	 ('TEL','ko','032','032','032',NULL,'Y',NULL,NULL,NULL,NULL),
	 ('TEL','ko','033','033','033',NULL,'Y',NULL,NULL,NULL,NULL),
	 ('TEL','ko','041','041','041',NULL,'Y',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('TEL','ko','042','042','042',NULL,'Y',NULL,NULL,NULL,NULL),
	 ('TEL','ko','043','043','043',NULL,'Y',NULL,NULL,NULL,NULL),
	 ('TEL','ko','044','044','044',NULL,'Y',NULL,NULL,NULL,NULL),
	 ('TEL','ko','0507','0507','0507',NULL,'Y','','','',''),
	 ('TEL','ko','051','051','051',NULL,'Y',NULL,NULL,NULL,NULL),
	 ('TEL','ko','052','052','052',NULL,'Y',NULL,NULL,NULL,NULL),
	 ('TEL','ko','053','053','053',NULL,'Y',NULL,NULL,NULL,NULL),
	 ('TEL','ko','054','054','054',NULL,'Y',NULL,NULL,NULL,NULL),
	 ('TEL','ko','055','055','055',NULL,'Y',NULL,NULL,NULL,NULL),
	 ('TEL','ko','061','061','061',NULL,'Y',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('TEL','ko','062','062','062',NULL,'Y',NULL,NULL,NULL,NULL),
	 ('TEL','ko','063','063','063',NULL,'Y',NULL,NULL,NULL,NULL),
	 ('TEL','ko','064','064','064',NULL,'Y',NULL,NULL,NULL,NULL),
	 ('TEL','ko','070','070','070',NULL,'Y',NULL,NULL,NULL,NULL),
	 ('TEL','ko','080','080','080',NULL,'Y','','','',''),
	 ('WDR','ko','11000','서울특별시',NULL,1,'Y',NULL,NULL,NULL,NULL),
	 ('WDR','ko','12000','전남광주통합특별시',NULL,2,'Y',NULL,NULL,NULL,NULL),
	 ('WDR','ko','26000','부산광역시',NULL,3,'Y',NULL,NULL,NULL,NULL),
	 ('WDR','ko','27000','대구광역시',NULL,4,'Y',NULL,NULL,NULL,NULL),
	 ('WDR','ko','28000','인천광역시',NULL,5,'Y',NULL,NULL,NULL,NULL);
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('WDR','ko','30000','대전광역시',NULL,7,'Y',NULL,NULL,NULL,NULL),
	 ('WDR','ko','31000','울산광역시',NULL,8,'Y',NULL,NULL,NULL,NULL),
	 ('WDR','ko','36000','세종특별자치시','',9,'Y','','','',''),
	 ('WDR','ko','41000','경기도',NULL,10,'Y',NULL,NULL,NULL,NULL),
	 ('WDR','ko','43000','충청북도',NULL,12,'Y',NULL,NULL,NULL,NULL),
	 ('WDR','ko','44000','충청남도',NULL,12,'Y',NULL,NULL,NULL,NULL),
	 ('WDR','ko','47000','경상북도',NULL,16,'Y',NULL,NULL,NULL,NULL),
	 ('WDR','ko','48000','경상남도',NULL,17,'Y',NULL,NULL,NULL,NULL),
	 ('WDR','ko','50000','제주특별자치도',NULL,18,'Y',NULL,NULL,NULL,NULL),
	 ('WDR','ko','51000','강원특별자치도','',11,'Y','','','','');
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('WDR','ko','52000','전북특별자치도','',14,'Y','','','',''),
	 ('YYYY','ko','2022','2022','',1,'N','','','',''),
	 ('YYYY','ko','2023','2023',NULL,2,'Y',NULL,NULL,NULL,NULL),
	 ('YYYY','ko','2024','2024',NULL,3,'Y',NULL,NULL,NULL,NULL),
	 ('YYYY','ko','2025','2025',NULL,4,'Y',NULL,NULL,NULL,NULL),
	 ('YYYY','ko','2026','2026',NULL,5,'Y',NULL,NULL,NULL,NULL),
	 ('YYYY','ko','2027','2027','',6,'N','','','',''),
	 ('YYYY','ko','2028','2028','',7,'N','','','',''),
	 ('YYYY','ko','2029','2029','',8,'N','','','',''),
	 ('YYYY','ko','2030','2030','',9,'N','','','','');
INSERT INTO admin.op_common_code (code_type,language,id,label,detail,ordering,use_yn,up_id,code_value,extension_code,mapping_code) VALUES
	 ('YYYY','ko','2031','2031','',10,'N','','','','');
